// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sep_convolution_filter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sep_convolution_filter::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sep_convolution_filter::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> sep_convolution_filter::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> sep_convolution_filter::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<3> sep_convolution_filter::ap_ST_st5_fsm_2 = "100";
const sc_lv<32> sep_convolution_filter::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> sep_convolution_filter::ap_const_lv1_1 = "1";
const sc_lv<17> sep_convolution_filter::ap_const_lv17_0 = "00000000000000000";
const sc_lv<32> sep_convolution_filter::ap_const_lv32_1 = "1";
const sc_lv<1> sep_convolution_filter::ap_const_lv1_0 = "0";
const sc_lv<19> sep_convolution_filter::ap_const_lv19_0 = "0000000000000000000";
const sc_lv<9> sep_convolution_filter::ap_const_lv9_0 = "000000000";
const sc_lv<10> sep_convolution_filter::ap_const_lv10_0 = "0000000000";
const sc_lv<19> sep_convolution_filter::ap_const_lv19_4B461 = "1001011010001100001";
const sc_lv<19> sep_convolution_filter::ap_const_lv19_1 = "1";
const sc_lv<10> sep_convolution_filter::ap_const_lv10_281 = "1010000001";
const sc_lv<9> sep_convolution_filter::ap_const_lv9_1 = "1";
const sc_lv<9> sep_convolution_filter::ap_const_lv9_1E0 = "111100000";
const sc_lv<10> sep_convolution_filter::ap_const_lv10_280 = "1010000000";
const sc_lv<10> sep_convolution_filter::ap_const_lv10_1 = "1";
const sc_lv<5> sep_convolution_filter::ap_const_lv5_0 = "00000";
const sc_lv<3> sep_convolution_filter::ap_const_lv3_0 = "000";
const sc_lv<48> sep_convolution_filter::ap_const_lv48_1020409 = "1000000100000010000001001";
const sc_lv<48> sep_convolution_filter::ap_const_lv48_0 = "000000000000000000000000000000000000000000000000";
const sc_lv<32> sep_convolution_filter::ap_const_lv32_17 = "10111";
const sc_lv<32> sep_convolution_filter::ap_const_lv32_1F = "11111";
const sc_lv<32> sep_convolution_filter::ap_const_lv32_2F = "101111";
const sc_lv<32> sep_convolution_filter::ap_const_lv32_26 = "100110";
const sc_lv<8> sep_convolution_filter::ap_const_lv8_3F = "111111";
const sc_lv<24> sep_convolution_filter::ap_const_lv24_47 = "1000111";
const sc_lv<23> sep_convolution_filter::ap_const_lv23_7FFFEA = "11111111111111111101010";
const sc_lv<16> sep_convolution_filter::ap_const_lv16_FF8E = "1111111110001110";
const sc_lv<16> sep_convolution_filter::ap_const_lv16_43 = "1000011";
const sc_lv<32> sep_convolution_filter::ap_const_lv32_2 = "10";

sep_convolution_filter::sep_convolution_filter(sc_module_name name) : sc_module(name), mVcdFile(0) {
    line_buffer_V_0_U = new sep_convolution_filter_line_buffer_V_0("line_buffer_V_0_U");
    line_buffer_V_0_U->clk(ap_clk);
    line_buffer_V_0_U->reset(ap_rst_n_inv);
    line_buffer_V_0_U->address0(line_buffer_V_0_address0);
    line_buffer_V_0_U->ce0(line_buffer_V_0_ce0);
    line_buffer_V_0_U->q0(line_buffer_V_0_q0);
    line_buffer_V_0_U->address1(line_buffer_V_0_addr_reg_598);
    line_buffer_V_0_U->ce1(line_buffer_V_0_ce1);
    line_buffer_V_0_U->we1(line_buffer_V_0_we1);
    line_buffer_V_0_U->d1(line_buffer_V_1_q0);
    line_buffer_V_1_U = new sep_convolution_filter_line_buffer_V_0("line_buffer_V_1_U");
    line_buffer_V_1_U->clk(ap_clk);
    line_buffer_V_1_U->reset(ap_rst_n_inv);
    line_buffer_V_1_U->address0(line_buffer_V_1_address0);
    line_buffer_V_1_U->ce0(line_buffer_V_1_ce0);
    line_buffer_V_1_U->q0(line_buffer_V_1_q0);
    line_buffer_V_1_U->address1(line_buffer_V_1_address1);
    line_buffer_V_1_U->ce1(line_buffer_V_1_ce1);
    line_buffer_V_1_U->we1(line_buffer_V_1_we1);
    line_buffer_V_1_U->d1(in_temp_V_reg_613);
    sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1_U1 = new sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1<1,1,17,8,24,24>("sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1_U1");
    sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1_U1->din0(convolution_buffer_V_2);
    sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1_U1->din1(grp_fu_538_p1);
    sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1_U1->din2(grp_fu_547_p3);
    sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1_U1->dout(grp_fu_538_p3);
    sep_convolution_filter_mac_muladd_17s_6s_23s_24_1_U2 = new sep_convolution_filter_mac_muladd_17s_6s_23s_24_1<1,1,17,6,23,24>("sep_convolution_filter_mac_muladd_17s_6s_23s_24_1_U2");
    sep_convolution_filter_mac_muladd_17s_6s_23s_24_1_U2->din0(grp_fu_556_p3);
    sep_convolution_filter_mac_muladd_17s_6s_23s_24_1_U2->din1(grp_fu_547_p1);
    sep_convolution_filter_mac_muladd_17s_6s_23s_24_1_U2->din2(grp_fu_547_p2);
    sep_convolution_filter_mac_muladd_17s_6s_23s_24_1_U2->dout(grp_fu_547_p3);
    sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1_U3 = new sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1<1,1,8,8,16,17>("sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1_U3");
    sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1_U3->din0(grp_fu_556_p0);
    sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1_U3->din1(grp_fu_556_p1);
    sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1_U3->din2(grp_fu_566_p3);
    sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1_U3->dout(grp_fu_556_p3);
    sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1_U4 = new sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1<1,1,8,8,14,16>("sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1_U4");
    sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1_U4->din0(grp_fu_566_p0);
    sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1_U4->din1(grp_fu_566_p1);
    sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1_U4->din2(r_V_fu_368_p2);
    sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1_U4->dout(grp_fu_566_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_101);
    sensitive << ( in_img_V_TVALID );
    sensitive << ( exitcond_flatten_fu_203_p2 );
    sensitive << ( or_cond_fu_295_p2 );

    SC_METHOD(thread_ap_sig_20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_410);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_440);
    sensitive << ( out_img_V_TREADY );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_101 );

    SC_METHOD(thread_ap_sig_69);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_92);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_69 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_20 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_2);
    sensitive << ( ap_sig_410 );

    SC_METHOD(thread_ap_sig_ioackin_out_img_V_TREADY);
    sensitive << ( out_img_V_TREADY );
    sensitive << ( ap_reg_ioackin_out_img_V_TREADY );

    SC_METHOD(thread_col_1_fu_313_p2);
    sensitive << ( col_mid2_fu_221_p3 );

    SC_METHOD(thread_col_mid2_fu_221_p3);
    sensitive << ( col_reg_192 );
    sensitive << ( exitcond_fu_215_p2 );

    SC_METHOD(thread_exitcond_flatten_fu_203_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( indvar_flatten_reg_170 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );

    SC_METHOD(thread_exitcond_fu_215_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_flatten_fu_203_p2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( col_reg_192 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );

    SC_METHOD(thread_grp_fu_538_p1);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );

    SC_METHOD(thread_grp_fu_547_p1);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );

    SC_METHOD(thread_grp_fu_547_p2);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( grp_fu_547_p20 );

    SC_METHOD(thread_grp_fu_547_p20);
    sensitive << ( p_shl4_cast_fu_421_p1 );
    sensitive << ( p_shl3_cast_fu_409_p1 );

    SC_METHOD(thread_grp_fu_556_p0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( grp_fu_556_p00 );

    SC_METHOD(thread_grp_fu_556_p00);
    sensitive << ( window_V_2 );

    SC_METHOD(thread_grp_fu_556_p1);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );

    SC_METHOD(thread_grp_fu_566_p0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( grp_fu_566_p00 );

    SC_METHOD(thread_grp_fu_566_p00);
    sensitive << ( window_V_1 );

    SC_METHOD(thread_grp_fu_566_p1);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );

    SC_METHOD(thread_in_img_V_TDATA_blk_n);
    sensitive << ( in_img_V_TVALID );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond_flatten_fu_203_p2 );
    sensitive << ( or_cond_fu_295_p2 );

    SC_METHOD(thread_in_img_V_TREADY);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_flatten_fu_203_p2 );
    sensitive << ( or_cond_fu_295_p2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );

    SC_METHOD(thread_indvar_flatten_next_fu_209_p2);
    sensitive << ( indvar_flatten_reg_170 );

    SC_METHOD(thread_line_buffer_V_0_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_5_fu_289_p1 );

    SC_METHOD(thread_line_buffer_V_0_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );

    SC_METHOD(thread_line_buffer_V_0_ce1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );

    SC_METHOD(thread_line_buffer_V_0_we1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );
    sensitive << ( tmp_4_reg_594 );

    SC_METHOD(thread_line_buffer_V_1_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_5_fu_289_p1 );

    SC_METHOD(thread_line_buffer_V_1_address1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_8_fu_336_p1 );

    SC_METHOD(thread_line_buffer_V_1_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );

    SC_METHOD(thread_line_buffer_V_1_ce1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );

    SC_METHOD(thread_line_buffer_V_1_we1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );
    sensitive << ( or_cond_reg_609 );

    SC_METHOD(thread_mul_fu_456_p0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( grp_fu_538_p3 );

    SC_METHOD(thread_mul_fu_456_p2);
    sensitive << ( mul_fu_456_p0 );

    SC_METHOD(thread_neg_mul_fu_462_p2);
    sensitive << ( mul_fu_456_p2 );

    SC_METHOD(thread_neg_ti_fu_503_p2);
    sensitive << ( p_v_v_fu_495_p3 );

    SC_METHOD(thread_or_cond1_fu_307_p2);
    sensitive << ( tmp_2_mid2_fu_267_p3 );
    sensitive << ( tmp_9_fu_301_p2 );

    SC_METHOD(thread_or_cond_fu_295_p2);
    sensitive << ( tmp_4_fu_283_p2 );
    sensitive << ( tmp_mid2_fu_247_p3 );

    SC_METHOD(thread_out_img_V_TDATA);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( tmp_12_fu_523_p3 );

    SC_METHOD(thread_out_img_V_TDATA_blk_n);
    sensitive << ( out_img_V_TREADY );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );

    SC_METHOD(thread_out_img_V_TVALID);
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_reg_ioackin_out_img_V_TREADY );

    SC_METHOD(thread_p_shl1_cast_fu_352_p1);
    sensitive << ( p_shl1_fu_344_p3 );

    SC_METHOD(thread_p_shl1_fu_344_p3);
    sensitive << ( window_V_0 );

    SC_METHOD(thread_p_shl2_cast_fu_364_p1);
    sensitive << ( p_shl2_fu_356_p3 );

    SC_METHOD(thread_p_shl2_fu_356_p3);
    sensitive << ( window_V_0 );

    SC_METHOD(thread_p_shl3_cast_fu_409_p1);
    sensitive << ( tmp_fu_401_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_421_p1);
    sensitive << ( tmp_1_fu_413_p3 );

    SC_METHOD(thread_p_v_v_fu_495_p3);
    sensitive << ( tmp_2_fu_468_p3 );
    sensitive << ( tmp_3_fu_475_p4 );
    sensitive << ( tmp_6_fu_485_p4 );

    SC_METHOD(thread_r_V_fu_368_p2);
    sensitive << ( p_shl2_cast_fu_364_p1 );
    sensitive << ( p_shl1_cast_fu_352_p1 );

    SC_METHOD(thread_row_mid2_fu_275_p3);
    sensitive << ( row_reg_181 );
    sensitive << ( exitcond_fu_215_p2 );
    sensitive << ( row_s_fu_229_p2 );

    SC_METHOD(thread_row_s_fu_229_p2);
    sensitive << ( row_reg_181 );

    SC_METHOD(thread_tmp6_fu_241_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_flatten_fu_203_p2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( row_reg_181 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );

    SC_METHOD(thread_tmp_10_fu_509_p1);
    sensitive << ( neg_ti_fu_503_p2 );

    SC_METHOD(thread_tmp_11_fu_513_p4);
    sensitive << ( mul_fu_456_p2 );

    SC_METHOD(thread_tmp_12_fu_523_p3);
    sensitive << ( tmp_2_fu_468_p3 );
    sensitive << ( tmp_10_fu_509_p1 );
    sensitive << ( tmp_11_fu_513_p4 );

    SC_METHOD(thread_tmp_1_fu_413_p3);
    sensitive << ( convolution_buffer_V_1 );

    SC_METHOD(thread_tmp_2_fu_468_p3);
    sensitive << ( grp_fu_538_p3 );

    SC_METHOD(thread_tmp_2_mid1_fu_255_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_flatten_fu_203_p2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );
    sensitive << ( row_s_fu_229_p2 );

    SC_METHOD(thread_tmp_2_mid2_fu_267_p3);
    sensitive << ( exitcond_fu_215_p2 );
    sensitive << ( tmp_2_mid1_fu_255_p2 );
    sensitive << ( tmp_s_fu_261_p2 );

    SC_METHOD(thread_tmp_3_fu_475_p4);
    sensitive << ( neg_mul_fu_462_p2 );

    SC_METHOD(thread_tmp_4_fu_283_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_flatten_fu_203_p2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );
    sensitive << ( col_mid2_fu_221_p3 );

    SC_METHOD(thread_tmp_5_fu_289_p1);
    sensitive << ( col_mid2_fu_221_p3 );

    SC_METHOD(thread_tmp_6_fu_485_p4);
    sensitive << ( mul_fu_456_p2 );

    SC_METHOD(thread_tmp_8_fu_336_p1);
    sensitive << ( col_mid2_reg_584 );

    SC_METHOD(thread_tmp_9_fu_301_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_flatten_fu_203_p2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );
    sensitive << ( col_mid2_fu_221_p3 );

    SC_METHOD(thread_tmp_fu_401_p3);
    sensitive << ( convolution_buffer_V_1 );

    SC_METHOD(thread_tmp_mid1_fu_235_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_flatten_fu_203_p2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );
    sensitive << ( row_s_fu_229_p2 );

    SC_METHOD(thread_tmp_mid2_fu_247_p3);
    sensitive << ( exitcond_fu_215_p2 );
    sensitive << ( tmp_mid1_fu_235_p2 );
    sensitive << ( tmp6_fu_241_p2 );

    SC_METHOD(thread_tmp_s_fu_261_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_flatten_fu_203_p2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( row_reg_181 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_flatten_fu_203_p2 );
    sensitive << ( ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_ioackin_out_img_V_TREADY );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    window_V_0 = "00000000";
    window_V_1 = "00000000";
    window_V_2 = "00000000";
    convolution_buffer_V_1 = "00000000000000000";
    convolution_buffer_V_2 = "00000000000000000";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ioackin_out_img_V_TREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sep_convolution_filter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_img_V_TDATA, "(port)in_img_V_TDATA");
    sc_trace(mVcdFile, in_img_V_TVALID, "(port)in_img_V_TVALID");
    sc_trace(mVcdFile, in_img_V_TREADY, "(port)in_img_V_TREADY");
    sc_trace(mVcdFile, out_img_V_TDATA, "(port)out_img_V_TDATA");
    sc_trace(mVcdFile, out_img_V_TVALID, "(port)out_img_V_TVALID");
    sc_trace(mVcdFile, out_img_V_TREADY, "(port)out_img_V_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_20, "ap_sig_20");
    sc_trace(mVcdFile, line_buffer_V_0_address0, "line_buffer_V_0_address0");
    sc_trace(mVcdFile, line_buffer_V_0_ce0, "line_buffer_V_0_ce0");
    sc_trace(mVcdFile, line_buffer_V_0_q0, "line_buffer_V_0_q0");
    sc_trace(mVcdFile, line_buffer_V_0_ce1, "line_buffer_V_0_ce1");
    sc_trace(mVcdFile, line_buffer_V_0_we1, "line_buffer_V_0_we1");
    sc_trace(mVcdFile, window_V_0, "window_V_0");
    sc_trace(mVcdFile, line_buffer_V_1_address0, "line_buffer_V_1_address0");
    sc_trace(mVcdFile, line_buffer_V_1_ce0, "line_buffer_V_1_ce0");
    sc_trace(mVcdFile, line_buffer_V_1_q0, "line_buffer_V_1_q0");
    sc_trace(mVcdFile, line_buffer_V_1_address1, "line_buffer_V_1_address1");
    sc_trace(mVcdFile, line_buffer_V_1_ce1, "line_buffer_V_1_ce1");
    sc_trace(mVcdFile, line_buffer_V_1_we1, "line_buffer_V_1_we1");
    sc_trace(mVcdFile, window_V_1, "window_V_1");
    sc_trace(mVcdFile, window_V_2, "window_V_2");
    sc_trace(mVcdFile, convolution_buffer_V_1, "convolution_buffer_V_1");
    sc_trace(mVcdFile, convolution_buffer_V_2, "convolution_buffer_V_2");
    sc_trace(mVcdFile, in_img_V_TDATA_blk_n, "in_img_V_TDATA_blk_n");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_69, "ap_sig_69");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, exitcond_flatten_fu_203_p2, "exitcond_flatten_fu_203_p2");
    sc_trace(mVcdFile, or_cond_fu_295_p2, "or_cond_fu_295_p2");
    sc_trace(mVcdFile, out_img_V_TDATA_blk_n, "out_img_V_TDATA_blk_n");
    sc_trace(mVcdFile, or_cond1_reg_619, "or_cond1_reg_619");
    sc_trace(mVcdFile, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1, "ap_reg_ppstg_or_cond1_reg_619_pp0_iter1");
    sc_trace(mVcdFile, indvar_flatten_reg_170, "indvar_flatten_reg_170");
    sc_trace(mVcdFile, row_reg_181, "row_reg_181");
    sc_trace(mVcdFile, col_reg_192, "col_reg_192");
    sc_trace(mVcdFile, ap_sig_101, "ap_sig_101");
    sc_trace(mVcdFile, ap_sig_ioackin_out_img_V_TREADY, "ap_sig_ioackin_out_img_V_TREADY");
    sc_trace(mVcdFile, indvar_flatten_next_fu_209_p2, "indvar_flatten_next_fu_209_p2");
    sc_trace(mVcdFile, col_mid2_fu_221_p3, "col_mid2_fu_221_p3");
    sc_trace(mVcdFile, col_mid2_reg_584, "col_mid2_reg_584");
    sc_trace(mVcdFile, row_mid2_fu_275_p3, "row_mid2_fu_275_p3");
    sc_trace(mVcdFile, tmp_4_fu_283_p2, "tmp_4_fu_283_p2");
    sc_trace(mVcdFile, tmp_4_reg_594, "tmp_4_reg_594");
    sc_trace(mVcdFile, line_buffer_V_0_addr_reg_598, "line_buffer_V_0_addr_reg_598");
    sc_trace(mVcdFile, or_cond_reg_609, "or_cond_reg_609");
    sc_trace(mVcdFile, in_temp_V_reg_613, "in_temp_V_reg_613");
    sc_trace(mVcdFile, or_cond1_fu_307_p2, "or_cond1_fu_307_p2");
    sc_trace(mVcdFile, col_1_fu_313_p2, "col_1_fu_313_p2");
    sc_trace(mVcdFile, tmp_5_fu_289_p1, "tmp_5_fu_289_p1");
    sc_trace(mVcdFile, tmp_8_fu_336_p1, "tmp_8_fu_336_p1");
    sc_trace(mVcdFile, grp_fu_556_p3, "grp_fu_556_p3");
    sc_trace(mVcdFile, ap_reg_ioackin_out_img_V_TREADY, "ap_reg_ioackin_out_img_V_TREADY");
    sc_trace(mVcdFile, exitcond_fu_215_p2, "exitcond_fu_215_p2");
    sc_trace(mVcdFile, row_s_fu_229_p2, "row_s_fu_229_p2");
    sc_trace(mVcdFile, tmp_mid1_fu_235_p2, "tmp_mid1_fu_235_p2");
    sc_trace(mVcdFile, tmp6_fu_241_p2, "tmp6_fu_241_p2");
    sc_trace(mVcdFile, tmp_2_mid1_fu_255_p2, "tmp_2_mid1_fu_255_p2");
    sc_trace(mVcdFile, tmp_s_fu_261_p2, "tmp_s_fu_261_p2");
    sc_trace(mVcdFile, tmp_mid2_fu_247_p3, "tmp_mid2_fu_247_p3");
    sc_trace(mVcdFile, tmp_2_mid2_fu_267_p3, "tmp_2_mid2_fu_267_p3");
    sc_trace(mVcdFile, tmp_9_fu_301_p2, "tmp_9_fu_301_p2");
    sc_trace(mVcdFile, p_shl1_fu_344_p3, "p_shl1_fu_344_p3");
    sc_trace(mVcdFile, p_shl2_fu_356_p3, "p_shl2_fu_356_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_364_p1, "p_shl2_cast_fu_364_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_352_p1, "p_shl1_cast_fu_352_p1");
    sc_trace(mVcdFile, r_V_fu_368_p2, "r_V_fu_368_p2");
    sc_trace(mVcdFile, grp_fu_566_p3, "grp_fu_566_p3");
    sc_trace(mVcdFile, tmp_fu_401_p3, "tmp_fu_401_p3");
    sc_trace(mVcdFile, tmp_1_fu_413_p3, "tmp_1_fu_413_p3");
    sc_trace(mVcdFile, p_shl4_cast_fu_421_p1, "p_shl4_cast_fu_421_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_409_p1, "p_shl3_cast_fu_409_p1");
    sc_trace(mVcdFile, grp_fu_538_p3, "grp_fu_538_p3");
    sc_trace(mVcdFile, mul_fu_456_p0, "mul_fu_456_p0");
    sc_trace(mVcdFile, mul_fu_456_p2, "mul_fu_456_p2");
    sc_trace(mVcdFile, neg_mul_fu_462_p2, "neg_mul_fu_462_p2");
    sc_trace(mVcdFile, tmp_2_fu_468_p3, "tmp_2_fu_468_p3");
    sc_trace(mVcdFile, tmp_3_fu_475_p4, "tmp_3_fu_475_p4");
    sc_trace(mVcdFile, tmp_6_fu_485_p4, "tmp_6_fu_485_p4");
    sc_trace(mVcdFile, p_v_v_fu_495_p3, "p_v_v_fu_495_p3");
    sc_trace(mVcdFile, neg_ti_fu_503_p2, "neg_ti_fu_503_p2");
    sc_trace(mVcdFile, tmp_10_fu_509_p1, "tmp_10_fu_509_p1");
    sc_trace(mVcdFile, tmp_11_fu_513_p4, "tmp_11_fu_513_p4");
    sc_trace(mVcdFile, tmp_12_fu_523_p3, "tmp_12_fu_523_p3");
    sc_trace(mVcdFile, grp_fu_538_p1, "grp_fu_538_p1");
    sc_trace(mVcdFile, grp_fu_547_p3, "grp_fu_547_p3");
    sc_trace(mVcdFile, grp_fu_547_p1, "grp_fu_547_p1");
    sc_trace(mVcdFile, grp_fu_547_p2, "grp_fu_547_p2");
    sc_trace(mVcdFile, grp_fu_556_p0, "grp_fu_556_p0");
    sc_trace(mVcdFile, grp_fu_556_p1, "grp_fu_556_p1");
    sc_trace(mVcdFile, grp_fu_566_p0, "grp_fu_566_p0");
    sc_trace(mVcdFile, grp_fu_566_p1, "grp_fu_566_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_2, "ap_sig_cseq_ST_st5_fsm_2");
    sc_trace(mVcdFile, ap_sig_410, "ap_sig_410");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_547_p20, "grp_fu_547_p20");
    sc_trace(mVcdFile, grp_fu_556_p00, "grp_fu_556_p00");
    sc_trace(mVcdFile, grp_fu_566_p00, "grp_fu_566_p00");
    sc_trace(mVcdFile, ap_sig_440, "ap_sig_440");
    sc_trace(mVcdFile, ap_sig_92, "ap_sig_92");
#endif

    }
    mHdltvinHandle.open("sep_convolution_filter.hdltvin.dat");
    mHdltvoutHandle.open("sep_convolution_filter.hdltvout.dat");
}

sep_convolution_filter::~sep_convolution_filter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete line_buffer_V_0_U;
    delete line_buffer_V_1_U;
    delete sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1_U1;
    delete sep_convolution_filter_mac_muladd_17s_6s_23s_24_1_U2;
    delete sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1_U3;
    delete sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1_U4;
}

void sep_convolution_filter::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_out_img_V_TREADY = ap_const_logic_0;
    } else {
        if (ap_sig_92.read()) {
            if (!((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read())))) {
                ap_reg_ioackin_out_img_V_TREADY = ap_const_logic_0;
            } else if (ap_sig_440.read()) {
                ap_reg_ioackin_out_img_V_TREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))) && 
             !esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && 
             !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
                     !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))) && 
                     !esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (!((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read())))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        col_reg_192 = col_1_fu_313_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        col_reg_192 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        indvar_flatten_reg_170 = indvar_flatten_next_fu_209_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten_reg_170 = ap_const_lv19_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        row_reg_181 = row_mid2_fu_275_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        row_reg_181 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 = or_cond1_reg_619.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        col_mid2_reg_584 = col_mid2_fu_221_p3.read();
        or_cond1_reg_619 = or_cond1_fu_307_p2.read();
        or_cond_reg_609 = or_cond_fu_295_p2.read();
        tmp_4_reg_594 = tmp_4_fu_283_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        convolution_buffer_V_1 = convolution_buffer_V_2.read();
        convolution_buffer_V_2 = grp_fu_556_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_295_p2.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        in_temp_V_reg_613 = in_img_V_TDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_fu_283_p2.read()))) {
        line_buffer_V_0_addr_reg_598 =  (sc_lv<10>) (tmp_5_fu_289_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_reg_594.read()))) {
        window_V_0 = line_buffer_V_0_q0.read();
        window_V_1 = line_buffer_V_1_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))) && !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_reg_609.read()))) {
        window_V_2 = in_temp_V_reg_613.read();
    }
}

void sep_convolution_filter::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_2.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void sep_convolution_filter::thread_ap_sig_101() {
    ap_sig_101 = (esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_295_p2.read()) && esl_seteq<1,1,1>(in_img_V_TVALID.read(), ap_const_logic_0));
}

void sep_convolution_filter::thread_ap_sig_20() {
    ap_sig_20 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void sep_convolution_filter::thread_ap_sig_410() {
    ap_sig_410 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void sep_convolution_filter::thread_ap_sig_440() {
    ap_sig_440 = (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_101.read()) && esl_seteq<1,1,1>(ap_const_logic_1, out_img_V_TREADY.read()));
}

void sep_convolution_filter::thread_ap_sig_69() {
    ap_sig_69 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void sep_convolution_filter::thread_ap_sig_92() {
    ap_sig_92 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()));
}

void sep_convolution_filter::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_69.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_20.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_ap_sig_cseq_ST_st5_fsm_2() {
    if (ap_sig_410.read()) {
        ap_sig_cseq_ST_st5_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_2 = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_ap_sig_ioackin_out_img_V_TREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_out_img_V_TREADY.read())) {
        ap_sig_ioackin_out_img_V_TREADY = out_img_V_TREADY.read();
    } else {
        ap_sig_ioackin_out_img_V_TREADY = ap_const_logic_1;
    }
}

void sep_convolution_filter::thread_col_1_fu_313_p2() {
    col_1_fu_313_p2 = (!col_mid2_fu_221_p3.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(col_mid2_fu_221_p3.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void sep_convolution_filter::thread_col_mid2_fu_221_p3() {
    col_mid2_fu_221_p3 = (!exitcond_fu_215_p2.read()[0].is_01())? sc_lv<10>(): ((exitcond_fu_215_p2.read()[0].to_bool())? ap_const_lv10_0: col_reg_192.read());
}

void sep_convolution_filter::thread_exitcond_flatten_fu_203_p2() {
    exitcond_flatten_fu_203_p2 = (!indvar_flatten_reg_170.read().is_01() || !ap_const_lv19_4B461.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_170.read() == ap_const_lv19_4B461);
}

void sep_convolution_filter::thread_exitcond_fu_215_p2() {
    exitcond_fu_215_p2 = (!col_reg_192.read().is_01() || !ap_const_lv10_281.is_01())? sc_lv<1>(): sc_lv<1>(col_reg_192.read() == ap_const_lv10_281);
}

void sep_convolution_filter::thread_grp_fu_538_p1() {
    grp_fu_538_p1 =  (sc_lv<8>) (ap_const_lv24_47);
}

void sep_convolution_filter::thread_grp_fu_547_p1() {
    grp_fu_547_p1 =  (sc_lv<6>) (ap_const_lv23_7FFFEA);
}

void sep_convolution_filter::thread_grp_fu_547_p2() {
    grp_fu_547_p2 =  (sc_lv<23>) (grp_fu_547_p20.read());
}

void sep_convolution_filter::thread_grp_fu_547_p20() {
    grp_fu_547_p20 = (!p_shl4_cast_fu_421_p1.read().is_01() || !p_shl3_cast_fu_409_p1.read().is_01())? sc_lv<24>(): (sc_bigint<24>(p_shl4_cast_fu_421_p1.read()) - sc_bigint<24>(p_shl3_cast_fu_409_p1.read()));
}

void sep_convolution_filter::thread_grp_fu_556_p0() {
    grp_fu_556_p0 =  (sc_lv<8>) (grp_fu_556_p00.read());
}

void sep_convolution_filter::thread_grp_fu_556_p00() {
    grp_fu_556_p00 = esl_zext<16,8>(window_V_2.read());
}

void sep_convolution_filter::thread_grp_fu_556_p1() {
    grp_fu_556_p1 =  (sc_lv<8>) (ap_const_lv16_FF8E);
}

void sep_convolution_filter::thread_grp_fu_566_p0() {
    grp_fu_566_p0 =  (sc_lv<8>) (grp_fu_566_p00.read());
}

void sep_convolution_filter::thread_grp_fu_566_p00() {
    grp_fu_566_p00 = esl_zext<16,8>(window_V_1.read());
}

void sep_convolution_filter::thread_grp_fu_566_p1() {
    grp_fu_566_p1 =  (sc_lv<8>) (ap_const_lv16_43);
}

void sep_convolution_filter::thread_in_img_V_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_295_p2.read()))) {
        in_img_V_TDATA_blk_n = in_img_V_TVALID.read();
    } else {
        in_img_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void sep_convolution_filter::thread_in_img_V_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_fu_295_p2.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        in_img_V_TREADY = ap_const_logic_1;
    } else {
        in_img_V_TREADY = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_indvar_flatten_next_fu_209_p2() {
    indvar_flatten_next_fu_209_p2 = (!indvar_flatten_reg_170.read().is_01() || !ap_const_lv19_1.is_01())? sc_lv<19>(): (sc_biguint<19>(indvar_flatten_reg_170.read()) + sc_biguint<19>(ap_const_lv19_1));
}

void sep_convolution_filter::thread_line_buffer_V_0_address0() {
    line_buffer_V_0_address0 =  (sc_lv<10>) (tmp_5_fu_289_p1.read());
}

void sep_convolution_filter::thread_line_buffer_V_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        line_buffer_V_0_ce0 = ap_const_logic_1;
    } else {
        line_buffer_V_0_ce0 = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_line_buffer_V_0_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        line_buffer_V_0_ce1 = ap_const_logic_1;
    } else {
        line_buffer_V_0_ce1 = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_line_buffer_V_0_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_reg_594.read())))) {
        line_buffer_V_0_we1 = ap_const_logic_1;
    } else {
        line_buffer_V_0_we1 = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_line_buffer_V_1_address0() {
    line_buffer_V_1_address0 =  (sc_lv<10>) (tmp_5_fu_289_p1.read());
}

void sep_convolution_filter::thread_line_buffer_V_1_address1() {
    line_buffer_V_1_address1 =  (sc_lv<10>) (tmp_8_fu_336_p1.read());
}

void sep_convolution_filter::thread_line_buffer_V_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        line_buffer_V_1_ce0 = ap_const_logic_1;
    } else {
        line_buffer_V_1_ce0 = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_line_buffer_V_1_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))))) {
        line_buffer_V_1_ce1 = ap_const_logic_1;
    } else {
        line_buffer_V_1_ce1 = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_line_buffer_V_1_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond_reg_609.read())))) {
        line_buffer_V_1_we1 = ap_const_logic_1;
    } else {
        line_buffer_V_1_we1 = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_mul_fu_456_p0() {
    mul_fu_456_p0 = grp_fu_538_p3.read();
}

void sep_convolution_filter::thread_mul_fu_456_p2() {
    mul_fu_456_p2 = (!mul_fu_456_p0.read().is_01() || !ap_const_lv48_1020409.is_01())? sc_lv<48>(): sc_bigint<24>(mul_fu_456_p0.read()) * sc_biguint<48>(ap_const_lv48_1020409);
}

void sep_convolution_filter::thread_neg_mul_fu_462_p2() {
    neg_mul_fu_462_p2 = (!ap_const_lv48_0.is_01() || !mul_fu_456_p2.read().is_01())? sc_lv<48>(): (sc_biguint<48>(ap_const_lv48_0) - sc_biguint<48>(mul_fu_456_p2.read()));
}

void sep_convolution_filter::thread_neg_ti_fu_503_p2() {
    neg_ti_fu_503_p2 = (!ap_const_lv17_0.is_01() || !p_v_v_fu_495_p3.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_biguint<17>(p_v_v_fu_495_p3.read()));
}

void sep_convolution_filter::thread_or_cond1_fu_307_p2() {
    or_cond1_fu_307_p2 = (tmp_2_mid2_fu_267_p3.read() & tmp_9_fu_301_p2.read());
}

void sep_convolution_filter::thread_or_cond_fu_295_p2() {
    or_cond_fu_295_p2 = (tmp_4_fu_283_p2.read() & tmp_mid2_fu_247_p3.read());
}

void sep_convolution_filter::thread_out_img_V_TDATA() {
    out_img_V_TDATA = (!tmp_12_fu_523_p3.read().is_01() || !ap_const_lv8_3F.is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_12_fu_523_p3.read()) + sc_biguint<8>(ap_const_lv8_3F));
}

void sep_convolution_filter::thread_out_img_V_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()))) {
        out_img_V_TDATA_blk_n = out_img_V_TREADY.read();
    } else {
        out_img_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void sep_convolution_filter::thread_out_img_V_TVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && ap_sig_101.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_out_img_V_TREADY.read()))) {
        out_img_V_TVALID = ap_const_logic_1;
    } else {
        out_img_V_TVALID = ap_const_logic_0;
    }
}

void sep_convolution_filter::thread_p_shl1_cast_fu_352_p1() {
    p_shl1_cast_fu_352_p1 = esl_zext<14,13>(p_shl1_fu_344_p3.read());
}

void sep_convolution_filter::thread_p_shl1_fu_344_p3() {
    p_shl1_fu_344_p3 = esl_concat<8,5>(window_V_0.read(), ap_const_lv5_0);
}

void sep_convolution_filter::thread_p_shl2_cast_fu_364_p1() {
    p_shl2_cast_fu_364_p1 = esl_zext<14,11>(p_shl2_fu_356_p3.read());
}

void sep_convolution_filter::thread_p_shl2_fu_356_p3() {
    p_shl2_fu_356_p3 = esl_concat<8,3>(window_V_0.read(), ap_const_lv3_0);
}

void sep_convolution_filter::thread_p_shl3_cast_fu_409_p1() {
    p_shl3_cast_fu_409_p1 = esl_sext<24,22>(tmp_fu_401_p3.read());
}

void sep_convolution_filter::thread_p_shl4_cast_fu_421_p1() {
    p_shl4_cast_fu_421_p1 = esl_sext<24,20>(tmp_1_fu_413_p3.read());
}

void sep_convolution_filter::thread_p_v_v_fu_495_p3() {
    p_v_v_fu_495_p3 = (!tmp_2_fu_468_p3.read()[0].is_01())? sc_lv<17>(): ((tmp_2_fu_468_p3.read()[0].to_bool())? tmp_3_fu_475_p4.read(): tmp_6_fu_485_p4.read());
}

void sep_convolution_filter::thread_r_V_fu_368_p2() {
    r_V_fu_368_p2 = (!p_shl2_cast_fu_364_p1.read().is_01() || !p_shl1_cast_fu_352_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(p_shl2_cast_fu_364_p1.read()) - sc_biguint<14>(p_shl1_cast_fu_352_p1.read()));
}

void sep_convolution_filter::thread_row_mid2_fu_275_p3() {
    row_mid2_fu_275_p3 = (!exitcond_fu_215_p2.read()[0].is_01())? sc_lv<9>(): ((exitcond_fu_215_p2.read()[0].to_bool())? row_s_fu_229_p2.read(): row_reg_181.read());
}

void sep_convolution_filter::thread_row_s_fu_229_p2() {
    row_s_fu_229_p2 = (!row_reg_181.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(row_reg_181.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void sep_convolution_filter::thread_tmp6_fu_241_p2() {
    tmp6_fu_241_p2 = (!row_reg_181.read().is_01() || !ap_const_lv9_1E0.is_01())? sc_lv<1>(): (sc_biguint<9>(row_reg_181.read()) < sc_biguint<9>(ap_const_lv9_1E0));
}

void sep_convolution_filter::thread_tmp_10_fu_509_p1() {
    tmp_10_fu_509_p1 = neg_ti_fu_503_p2.read().range(8-1, 0);
}

void sep_convolution_filter::thread_tmp_11_fu_513_p4() {
    tmp_11_fu_513_p4 = mul_fu_456_p2.read().range(38, 31);
}

void sep_convolution_filter::thread_tmp_12_fu_523_p3() {
    tmp_12_fu_523_p3 = (!tmp_2_fu_468_p3.read()[0].is_01())? sc_lv<8>(): ((tmp_2_fu_468_p3.read()[0].to_bool())? tmp_10_fu_509_p1.read(): tmp_11_fu_513_p4.read());
}

void sep_convolution_filter::thread_tmp_1_fu_413_p3() {
    tmp_1_fu_413_p3 = esl_concat<17,3>(convolution_buffer_V_1.read(), ap_const_lv3_0);
}

void sep_convolution_filter::thread_tmp_2_fu_468_p3() {
    tmp_2_fu_468_p3 = grp_fu_538_p3.read().range(23, 23);
}

void sep_convolution_filter::thread_tmp_2_mid1_fu_255_p2() {
    tmp_2_mid1_fu_255_p2 = (!row_s_fu_229_p2.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(row_s_fu_229_p2.read() != ap_const_lv9_0);
}

void sep_convolution_filter::thread_tmp_2_mid2_fu_267_p3() {
    tmp_2_mid2_fu_267_p3 = (!exitcond_fu_215_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_fu_215_p2.read()[0].to_bool())? tmp_2_mid1_fu_255_p2.read(): tmp_s_fu_261_p2.read());
}

void sep_convolution_filter::thread_tmp_3_fu_475_p4() {
    tmp_3_fu_475_p4 = neg_mul_fu_462_p2.read().range(47, 31);
}

void sep_convolution_filter::thread_tmp_4_fu_283_p2() {
    tmp_4_fu_283_p2 = (!col_mid2_fu_221_p3.read().is_01() || !ap_const_lv10_280.is_01())? sc_lv<1>(): (sc_biguint<10>(col_mid2_fu_221_p3.read()) < sc_biguint<10>(ap_const_lv10_280));
}

void sep_convolution_filter::thread_tmp_5_fu_289_p1() {
    tmp_5_fu_289_p1 = esl_zext<64,10>(col_mid2_fu_221_p3.read());
}

void sep_convolution_filter::thread_tmp_6_fu_485_p4() {
    tmp_6_fu_485_p4 = mul_fu_456_p2.read().range(47, 31);
}

void sep_convolution_filter::thread_tmp_8_fu_336_p1() {
    tmp_8_fu_336_p1 = esl_zext<64,10>(col_mid2_reg_584.read());
}

void sep_convolution_filter::thread_tmp_9_fu_301_p2() {
    tmp_9_fu_301_p2 = (!col_mid2_fu_221_p3.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(col_mid2_fu_221_p3.read() != ap_const_lv10_0);
}

void sep_convolution_filter::thread_tmp_fu_401_p3() {
    tmp_fu_401_p3 = esl_concat<17,5>(convolution_buffer_V_1.read(), ap_const_lv5_0);
}

void sep_convolution_filter::thread_tmp_mid1_fu_235_p2() {
    tmp_mid1_fu_235_p2 = (!row_s_fu_229_p2.read().is_01() || !ap_const_lv9_1E0.is_01())? sc_lv<1>(): (sc_biguint<9>(row_s_fu_229_p2.read()) < sc_biguint<9>(ap_const_lv9_1E0));
}

void sep_convolution_filter::thread_tmp_mid2_fu_247_p3() {
    tmp_mid2_fu_247_p3 = (!exitcond_fu_215_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_fu_215_p2.read()[0].to_bool())? tmp_mid1_fu_235_p2.read(): tmp6_fu_241_p2.read());
}

void sep_convolution_filter::thread_tmp_s_fu_261_p2() {
    tmp_s_fu_261_p2 = (!row_reg_181.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(row_reg_181.read() != ap_const_lv9_0);
}

void sep_convolution_filter::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))) && !esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  ap_sig_101.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_or_cond1_reg_619_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_out_img_V_TREADY.read()))) && 
  !esl_seteq<1,1,1>(exitcond_flatten_fu_203_p2.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_st5_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void sep_convolution_filter::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_img_V_TDATA\" :  \"" << in_img_V_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_img_V_TVALID\" :  \"" << in_img_V_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_img_V_TREADY\" :  \"" << in_img_V_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_img_V_TDATA\" :  \"" << out_img_V_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_img_V_TVALID\" :  \"" << out_img_V_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"out_img_V_TREADY\" :  \"" << out_img_V_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

