// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _sep_convolution_filter_HH_
#define _sep_convolution_filter_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1.h"
#include "sep_convolution_filter_mac_muladd_17s_6s_23s_24_1.h"
#include "sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1.h"
#include "sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1.h"
#include "sep_convolution_filter_line_buffer_V_0.h"

namespace ap_rtl {

struct sep_convolution_filter : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > in_img_V_TDATA;
    sc_in< sc_logic > in_img_V_TVALID;
    sc_out< sc_logic > in_img_V_TREADY;
    sc_out< sc_lv<8> > out_img_V_TDATA;
    sc_out< sc_logic > out_img_V_TVALID;
    sc_in< sc_logic > out_img_V_TREADY;


    // Module declarations
    sep_convolution_filter(sc_module_name name);
    SC_HAS_PROCESS(sep_convolution_filter);

    ~sep_convolution_filter();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sep_convolution_filter_line_buffer_V_0* line_buffer_V_0_U;
    sep_convolution_filter_line_buffer_V_0* line_buffer_V_1_U;
    sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1<1,1,17,8,24,24>* sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1_U1;
    sep_convolution_filter_mac_muladd_17s_6s_23s_24_1<1,1,17,6,23,24>* sep_convolution_filter_mac_muladd_17s_6s_23s_24_1_U2;
    sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1<1,1,8,8,16,17>* sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1_U3;
    sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1<1,1,8,8,14,16>* sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1_U4;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_20;
    sc_signal< sc_lv<10> > line_buffer_V_0_address0;
    sc_signal< sc_logic > line_buffer_V_0_ce0;
    sc_signal< sc_lv<8> > line_buffer_V_0_q0;
    sc_signal< sc_logic > line_buffer_V_0_ce1;
    sc_signal< sc_logic > line_buffer_V_0_we1;
    sc_signal< sc_lv<8> > window_V_0;
    sc_signal< sc_lv<10> > line_buffer_V_1_address0;
    sc_signal< sc_logic > line_buffer_V_1_ce0;
    sc_signal< sc_lv<8> > line_buffer_V_1_q0;
    sc_signal< sc_lv<10> > line_buffer_V_1_address1;
    sc_signal< sc_logic > line_buffer_V_1_ce1;
    sc_signal< sc_logic > line_buffer_V_1_we1;
    sc_signal< sc_lv<8> > window_V_1;
    sc_signal< sc_lv<8> > window_V_2;
    sc_signal< sc_lv<17> > convolution_buffer_V_1;
    sc_signal< sc_lv<17> > convolution_buffer_V_2;
    sc_signal< sc_logic > in_img_V_TDATA_blk_n;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_1;
    sc_signal< bool > ap_sig_69;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_lv<1> > exitcond_flatten_fu_203_p2;
    sc_signal< sc_lv<1> > or_cond_fu_295_p2;
    sc_signal< sc_logic > out_img_V_TDATA_blk_n;
    sc_signal< sc_lv<1> > or_cond1_reg_619;
    sc_signal< sc_lv<1> > ap_reg_ppstg_or_cond1_reg_619_pp0_iter1;
    sc_signal< sc_lv<19> > indvar_flatten_reg_170;
    sc_signal< sc_lv<9> > row_reg_181;
    sc_signal< sc_lv<10> > col_reg_192;
    sc_signal< bool > ap_sig_101;
    sc_signal< sc_logic > ap_sig_ioackin_out_img_V_TREADY;
    sc_signal< sc_lv<19> > indvar_flatten_next_fu_209_p2;
    sc_signal< sc_lv<10> > col_mid2_fu_221_p3;
    sc_signal< sc_lv<10> > col_mid2_reg_584;
    sc_signal< sc_lv<9> > row_mid2_fu_275_p3;
    sc_signal< sc_lv<1> > tmp_4_fu_283_p2;
    sc_signal< sc_lv<1> > tmp_4_reg_594;
    sc_signal< sc_lv<10> > line_buffer_V_0_addr_reg_598;
    sc_signal< sc_lv<1> > or_cond_reg_609;
    sc_signal< sc_lv<8> > in_temp_V_reg_613;
    sc_signal< sc_lv<1> > or_cond1_fu_307_p2;
    sc_signal< sc_lv<10> > col_1_fu_313_p2;
    sc_signal< sc_lv<64> > tmp_5_fu_289_p1;
    sc_signal< sc_lv<64> > tmp_8_fu_336_p1;
    sc_signal< sc_lv<17> > grp_fu_556_p3;
    sc_signal< sc_logic > ap_reg_ioackin_out_img_V_TREADY;
    sc_signal< sc_lv<1> > exitcond_fu_215_p2;
    sc_signal< sc_lv<9> > row_s_fu_229_p2;
    sc_signal< sc_lv<1> > tmp_mid1_fu_235_p2;
    sc_signal< sc_lv<1> > tmp6_fu_241_p2;
    sc_signal< sc_lv<1> > tmp_2_mid1_fu_255_p2;
    sc_signal< sc_lv<1> > tmp_s_fu_261_p2;
    sc_signal< sc_lv<1> > tmp_mid2_fu_247_p3;
    sc_signal< sc_lv<1> > tmp_2_mid2_fu_267_p3;
    sc_signal< sc_lv<1> > tmp_9_fu_301_p2;
    sc_signal< sc_lv<13> > p_shl1_fu_344_p3;
    sc_signal< sc_lv<11> > p_shl2_fu_356_p3;
    sc_signal< sc_lv<14> > p_shl2_cast_fu_364_p1;
    sc_signal< sc_lv<14> > p_shl1_cast_fu_352_p1;
    sc_signal< sc_lv<14> > r_V_fu_368_p2;
    sc_signal< sc_lv<16> > grp_fu_566_p3;
    sc_signal< sc_lv<22> > tmp_fu_401_p3;
    sc_signal< sc_lv<20> > tmp_1_fu_413_p3;
    sc_signal< sc_lv<24> > p_shl4_cast_fu_421_p1;
    sc_signal< sc_lv<24> > p_shl3_cast_fu_409_p1;
    sc_signal< sc_lv<24> > grp_fu_538_p3;
    sc_signal< sc_lv<24> > mul_fu_456_p0;
    sc_signal< sc_lv<48> > mul_fu_456_p2;
    sc_signal< sc_lv<48> > neg_mul_fu_462_p2;
    sc_signal< sc_lv<1> > tmp_2_fu_468_p3;
    sc_signal< sc_lv<17> > tmp_3_fu_475_p4;
    sc_signal< sc_lv<17> > tmp_6_fu_485_p4;
    sc_signal< sc_lv<17> > p_v_v_fu_495_p3;
    sc_signal< sc_lv<17> > neg_ti_fu_503_p2;
    sc_signal< sc_lv<8> > tmp_10_fu_509_p1;
    sc_signal< sc_lv<8> > tmp_11_fu_513_p4;
    sc_signal< sc_lv<8> > tmp_12_fu_523_p3;
    sc_signal< sc_lv<8> > grp_fu_538_p1;
    sc_signal< sc_lv<24> > grp_fu_547_p3;
    sc_signal< sc_lv<6> > grp_fu_547_p1;
    sc_signal< sc_lv<23> > grp_fu_547_p2;
    sc_signal< sc_lv<8> > grp_fu_556_p0;
    sc_signal< sc_lv<8> > grp_fu_556_p1;
    sc_signal< sc_lv<8> > grp_fu_566_p0;
    sc_signal< sc_lv<8> > grp_fu_566_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_2;
    sc_signal< bool > ap_sig_410;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_lv<24> > grp_fu_547_p20;
    sc_signal< sc_lv<16> > grp_fu_556_p00;
    sc_signal< sc_lv<16> > grp_fu_566_p00;
    sc_signal< bool > ap_sig_440;
    sc_signal< bool > ap_sig_92;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_st1_fsm_0;
    static const sc_lv<3> ap_ST_pp0_stg0_fsm_1;
    static const sc_lv<3> ap_ST_st5_fsm_2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<17> ap_const_lv17_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<19> ap_const_lv19_0;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<19> ap_const_lv19_4B461;
    static const sc_lv<19> ap_const_lv19_1;
    static const sc_lv<10> ap_const_lv10_281;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<9> ap_const_lv9_1E0;
    static const sc_lv<10> ap_const_lv10_280;
    static const sc_lv<10> ap_const_lv10_1;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<48> ap_const_lv48_1020409;
    static const sc_lv<48> ap_const_lv48_0;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_2F;
    static const sc_lv<32> ap_const_lv32_26;
    static const sc_lv<8> ap_const_lv8_3F;
    static const sc_lv<24> ap_const_lv24_47;
    static const sc_lv<23> ap_const_lv23_7FFFEA;
    static const sc_lv<16> ap_const_lv16_FF8E;
    static const sc_lv<16> ap_const_lv16_43;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_101();
    void thread_ap_sig_20();
    void thread_ap_sig_410();
    void thread_ap_sig_440();
    void thread_ap_sig_69();
    void thread_ap_sig_92();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_1();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st5_fsm_2();
    void thread_ap_sig_ioackin_out_img_V_TREADY();
    void thread_col_1_fu_313_p2();
    void thread_col_mid2_fu_221_p3();
    void thread_exitcond_flatten_fu_203_p2();
    void thread_exitcond_fu_215_p2();
    void thread_grp_fu_538_p1();
    void thread_grp_fu_547_p1();
    void thread_grp_fu_547_p2();
    void thread_grp_fu_547_p20();
    void thread_grp_fu_556_p0();
    void thread_grp_fu_556_p00();
    void thread_grp_fu_556_p1();
    void thread_grp_fu_566_p0();
    void thread_grp_fu_566_p00();
    void thread_grp_fu_566_p1();
    void thread_in_img_V_TDATA_blk_n();
    void thread_in_img_V_TREADY();
    void thread_indvar_flatten_next_fu_209_p2();
    void thread_line_buffer_V_0_address0();
    void thread_line_buffer_V_0_ce0();
    void thread_line_buffer_V_0_ce1();
    void thread_line_buffer_V_0_we1();
    void thread_line_buffer_V_1_address0();
    void thread_line_buffer_V_1_address1();
    void thread_line_buffer_V_1_ce0();
    void thread_line_buffer_V_1_ce1();
    void thread_line_buffer_V_1_we1();
    void thread_mul_fu_456_p0();
    void thread_mul_fu_456_p2();
    void thread_neg_mul_fu_462_p2();
    void thread_neg_ti_fu_503_p2();
    void thread_or_cond1_fu_307_p2();
    void thread_or_cond_fu_295_p2();
    void thread_out_img_V_TDATA();
    void thread_out_img_V_TDATA_blk_n();
    void thread_out_img_V_TVALID();
    void thread_p_shl1_cast_fu_352_p1();
    void thread_p_shl1_fu_344_p3();
    void thread_p_shl2_cast_fu_364_p1();
    void thread_p_shl2_fu_356_p3();
    void thread_p_shl3_cast_fu_409_p1();
    void thread_p_shl4_cast_fu_421_p1();
    void thread_p_v_v_fu_495_p3();
    void thread_r_V_fu_368_p2();
    void thread_row_mid2_fu_275_p3();
    void thread_row_s_fu_229_p2();
    void thread_tmp6_fu_241_p2();
    void thread_tmp_10_fu_509_p1();
    void thread_tmp_11_fu_513_p4();
    void thread_tmp_12_fu_523_p3();
    void thread_tmp_1_fu_413_p3();
    void thread_tmp_2_fu_468_p3();
    void thread_tmp_2_mid1_fu_255_p2();
    void thread_tmp_2_mid2_fu_267_p3();
    void thread_tmp_3_fu_475_p4();
    void thread_tmp_4_fu_283_p2();
    void thread_tmp_5_fu_289_p1();
    void thread_tmp_6_fu_485_p4();
    void thread_tmp_8_fu_336_p1();
    void thread_tmp_9_fu_301_p2();
    void thread_tmp_fu_401_p3();
    void thread_tmp_mid1_fu_235_p2();
    void thread_tmp_mid2_fu_247_p3();
    void thread_tmp_s_fu_261_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
