// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="convolution_filter,hls_ip_2016_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=41.666668,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=14.880000,HLS_SYN_LAT=310572,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=567,HLS_SYN_LUT=2568}" *)

module convolution_filter (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_img_V_TDATA,
        in_img_V_TVALID,
        in_img_V_TREADY,
        out_img_V_TDATA,
        out_img_V_TVALID,
        out_img_V_TREADY
);

parameter    ap_ST_st1_fsm_0 = 3'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 3'b10;
parameter    ap_ST_st5_fsm_2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv19_0 = 19'b0000000000000000000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv19_4BD29 = 19'b1001011110100101001;
parameter    ap_const_lv19_1 = 19'b1;
parameter    ap_const_lv10_283 = 10'b1010000011;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv9_1E0 = 9'b111100000;
parameter    ap_const_lv9_2 = 9'b10;
parameter    ap_const_lv10_280 = 10'b1010000000;
parameter    ap_const_lv10_2 = 10'b10;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv14_1E = 14'b11110;
parameter    ap_const_lv15_27 = 15'b100111;
parameter    ap_const_lv15_30 = 15'b110000;
parameter    ap_const_lv13_A = 13'b1010;
parameter    ap_const_lv14_13 = 14'b10011;
parameter    ap_const_lv14_1C = 14'b11100;
parameter    ap_const_lv15_26 = 15'b100110;
parameter    ap_const_lv15_2F = 15'b101111;
parameter    ap_const_lv12_7 = 12'b111;
parameter    ap_const_lv13_9 = 13'b1001;
parameter    ap_const_lv14_12 = 14'b10010;
parameter    ap_const_lv14_1B = 14'b11011;
parameter    ap_const_lv14_1D = 14'b11101;
parameter    ap_const_lv15_2E = 15'b101110;
parameter    ap_const_lv12_6 = 12'b110;
parameter    ap_const_lv14_11 = 14'b10001;
parameter    ap_const_lv14_1A = 14'b11010;
parameter    ap_const_lv15_23 = 15'b100011;
parameter    ap_const_lv15_25 = 15'b100101;
parameter    ap_const_lv12_5 = 12'b101;
parameter    ap_const_lv13_E = 13'b1110;
parameter    ap_const_lv14_19 = 14'b11001;
parameter    ap_const_lv15_22 = 15'b100010;
parameter    ap_const_lv15_24 = 15'b100100;
parameter    ap_const_lv15_2D = 15'b101101;
parameter    ap_const_lv13_D = 13'b1101;
parameter    ap_const_lv13_F = 13'b1111;
parameter    ap_const_lv14_18 = 14'b11000;
parameter    ap_const_lv15_21 = 15'b100001;
parameter    ap_const_lv15_2A = 15'b101010;
parameter    ap_const_lv15_2C = 15'b101100;
parameter    ap_const_lv14_15 = 14'b10101;
parameter    ap_const_lv14_17 = 14'b10111;
parameter    ap_const_lv15_29 = 15'b101001;
parameter    ap_const_lv15_2B = 15'b101011;
parameter    ap_const_lv11_3 = 11'b11;
parameter    ap_const_lv13_C = 13'b1100;
parameter    ap_const_lv14_16 = 14'b10110;
parameter    ap_const_lv14_1F = 14'b11111;
parameter    ap_const_lv15_28 = 15'b101000;
parameter    ap_const_lv15_31 = 15'b110001;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv13_B = 13'b1011;
parameter    ap_const_lv14_14 = 14'b10100;
parameter    ap_const_lv8_3 = 8'b11;
parameter    ap_const_lv8_4 = 8'b100;
parameter    ap_const_lv8_2 = 8'b10;
parameter    ap_const_lv8_5 = 8'b101;
parameter    ap_const_lv32_2 = 32'b10;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_img_V_TDATA;
input   in_img_V_TVALID;
output   in_img_V_TREADY;
output  [7:0] out_img_V_TDATA;
output   out_img_V_TVALID;
input   out_img_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_img_V_TREADY;
reg out_img_V_TVALID;

reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_20;
reg   [7:0] window_V_0_6;
reg   [7:0] window_V_1_6;
reg   [7:0] window_V_2_6;
reg   [7:0] window_V_3_6;
reg   [7:0] window_V_4_6;
reg   [7:0] window_V_5_6;
reg   [7:0] window_V_6_6;
wire   [9:0] line_buffer_V_0_address0;
reg    line_buffer_V_0_ce0;
wire   [7:0] line_buffer_V_0_q0;
reg    line_buffer_V_0_ce1;
reg    line_buffer_V_0_we1;
wire   [9:0] line_buffer_V_1_address0;
reg    line_buffer_V_1_ce0;
wire   [7:0] line_buffer_V_1_q0;
reg    line_buffer_V_1_ce1;
reg    line_buffer_V_1_we1;
wire   [9:0] line_buffer_V_2_address0;
reg    line_buffer_V_2_ce0;
wire   [7:0] line_buffer_V_2_q0;
reg    line_buffer_V_2_ce1;
reg    line_buffer_V_2_we1;
wire   [9:0] line_buffer_V_3_address0;
reg    line_buffer_V_3_ce0;
wire   [7:0] line_buffer_V_3_q0;
reg    line_buffer_V_3_ce1;
reg    line_buffer_V_3_we1;
wire   [9:0] line_buffer_V_4_address0;
reg    line_buffer_V_4_ce0;
wire   [7:0] line_buffer_V_4_q0;
reg    line_buffer_V_4_ce1;
reg    line_buffer_V_4_we1;
wire   [9:0] line_buffer_V_5_address0;
reg    line_buffer_V_5_ce0;
wire   [7:0] line_buffer_V_5_q0;
wire   [9:0] line_buffer_V_5_address1;
reg    line_buffer_V_5_ce1;
reg    line_buffer_V_5_we1;
reg   [7:0] window_V_0_1;
reg   [7:0] window_V_0_2;
reg   [7:0] window_V_0_3;
reg   [7:0] window_V_0_4;
reg   [7:0] window_V_0_5;
reg   [7:0] window_V_1_1;
reg   [7:0] window_V_1_2;
reg   [7:0] window_V_1_3;
reg   [7:0] window_V_1_4;
reg   [7:0] window_V_1_5;
reg   [7:0] window_V_2_1;
reg   [7:0] window_V_2_2;
reg   [7:0] window_V_2_3;
reg   [7:0] window_V_2_4;
reg   [7:0] window_V_2_5;
reg   [7:0] window_V_3_1;
reg   [7:0] window_V_3_2;
reg   [7:0] window_V_3_3;
reg   [7:0] window_V_3_4;
reg   [7:0] window_V_3_5;
reg   [7:0] window_V_4_1;
reg   [7:0] window_V_4_2;
reg   [7:0] window_V_4_3;
reg   [7:0] window_V_4_4;
reg   [7:0] window_V_4_5;
reg   [7:0] window_V_5_1;
reg   [7:0] window_V_5_2;
reg   [7:0] window_V_5_3;
reg   [7:0] window_V_5_4;
reg   [7:0] window_V_5_5;
reg   [7:0] window_V_6_1;
reg   [7:0] window_V_6_2;
reg   [7:0] window_V_6_3;
reg   [7:0] window_V_6_4;
reg   [7:0] window_V_6_5;
reg    in_img_V_TDATA_blk_n;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_149;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it2;
wire   [0:0] exitcond_flatten_fu_506_p2;
wire   [0:0] or_cond_fu_602_p2;
reg    out_img_V_TDATA_blk_n;
reg   [0:0] or_cond1_reg_2085;
reg   [0:0] ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1;
reg   [18:0] indvar_flatten_reg_410;
reg   [8:0] row_reg_421;
reg   [9:0] col_reg_432;
reg   [0:0] exitcond_flatten_reg_2017;
reg    ap_sig_181;
reg    ap_sig_ioackin_out_img_V_TREADY;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_2017_pp0_iter1;
wire   [18:0] indvar_flatten_next_fu_512_p2;
wire   [9:0] col_mid2_fu_524_p3;
reg   [9:0] col_mid2_reg_2026;
wire   [8:0] row_mid2_fu_578_p3;
wire   [0:0] tmp_4_fu_586_p2;
reg   [0:0] tmp_4_reg_2036;
reg   [9:0] line_buffer_V_0_addr_reg_2040;
reg   [9:0] line_buffer_V_1_addr_reg_2046;
reg   [9:0] line_buffer_V_2_addr_reg_2052;
reg   [9:0] line_buffer_V_3_addr_reg_2058;
reg   [9:0] line_buffer_V_4_addr_reg_2064;
reg   [0:0] or_cond_reg_2075;
reg   [7:0] in_temp_V_reg_2079;
wire   [0:0] or_cond1_fu_620_p2;
wire   [9:0] col_1_fu_626_p2;
reg   [7:0] in_temp_V_1_load_reg_2094;
reg   [7:0] window_V_5_6_loc_1_load_reg_2100;
reg   [7:0] window_V_4_6_loc_1_load_reg_2106;
reg   [7:0] window_V_3_6_loc_1_load_reg_2112;
reg   [7:0] window_V_2_6_loc_1_load_reg_2118;
reg   [7:0] window_V_1_6_loc_1_load_reg_2124;
reg   [7:0] window_V_0_6_loc_1_load_reg_2130;
wire   [63:0] tmp_6_fu_592_p1;
wire   [63:0] tmp_8_fu_719_p1;
reg   [7:0] in_temp_V_1_fu_266;
reg   [7:0] window_V_5_6_loc_1_fu_270;
reg   [7:0] window_V_4_6_loc_1_fu_274;
reg   [7:0] window_V_3_6_loc_1_fu_278;
reg   [7:0] window_V_2_6_loc_1_fu_282;
reg   [7:0] window_V_1_6_loc_1_fu_286;
reg   [7:0] window_V_0_6_loc_1_fu_290;
reg    ap_reg_ioackin_out_img_V_TREADY;
wire   [0:0] exitcond_fu_518_p2;
wire   [8:0] row_s_fu_532_p2;
wire   [0:0] tmp_mid1_fu_538_p2;
wire   [0:0] tmp_fu_544_p2;
wire   [0:0] tmp_2_mid1_fu_558_p2;
wire   [0:0] tmp_2_fu_564_p2;
wire   [0:0] tmp_mid2_fu_550_p3;
wire   [0:0] tmp_2_mid2_fu_570_p3;
wire   [0:0] tmp_9_fu_614_p2;
wire   [7:0] r_V_fu_1095_p0;
wire   [5:0] r_V_fu_1095_p1;
wire   [7:0] r_V_0_1_fu_1105_p0;
wire   [6:0] r_V_0_1_fu_1105_p1;
wire   [7:0] r_V_0_2_fu_1115_p0;
wire   [6:0] r_V_0_2_fu_1115_p1;
wire   [7:0] r_V_0_4_fu_1125_p0;
wire   [4:0] r_V_0_4_fu_1125_p1;
wire   [7:0] r_V_0_5_fu_1134_p0;
wire   [5:0] r_V_0_5_fu_1134_p1;
wire   [7:0] r_V_0_6_fu_1144_p0;
wire   [5:0] r_V_0_6_fu_1144_p1;
wire   [7:0] r_V_1_fu_1154_p0;
wire   [6:0] r_V_1_fu_1154_p1;
wire   [7:0] r_V_1_1_fu_1164_p0;
wire   [6:0] r_V_1_1_fu_1164_p1;
wire   [14:0] r_V_1_1_fu_1164_p2;
wire   [7:0] r_V_1_2_fu_1178_p0;
wire   [3:0] r_V_1_2_fu_1178_p1;
wire   [11:0] r_V_1_2_fu_1178_p2;
wire   [7:0] r_V_1_3_fu_1192_p0;
wire   [4:0] r_V_1_3_fu_1192_p1;
wire   [7:0] r_V_1_4_fu_1202_p0;
wire   [5:0] r_V_1_4_fu_1202_p1;
wire   [7:0] r_V_1_5_fu_1211_p0;
wire   [5:0] r_V_1_5_fu_1211_p1;
wire   [7:0] r_V_1_6_fu_1221_p0;
wire   [5:0] r_V_1_6_fu_1221_p1;
wire   [13:0] r_V_1_6_fu_1221_p2;
wire   [7:0] r_V_2_fu_1235_p0;
wire   [6:0] r_V_2_fu_1235_p1;
wire   [14:0] r_V_2_fu_1235_p2;
wire   [7:0] r_V_2_1_fu_1249_p0;
wire   [3:0] r_V_2_1_fu_1249_p1;
wire   [11:0] r_V_2_1_fu_1249_p2;
wire   [7:0] r_V_2_3_fu_1263_p0;
wire   [5:0] r_V_2_3_fu_1263_p1;
wire   [7:0] r_V_2_4_fu_1273_p0;
wire   [5:0] r_V_2_4_fu_1273_p1;
wire   [7:0] r_V_2_5_fu_1282_p0;
wire   [6:0] r_V_2_5_fu_1282_p1;
wire   [7:0] r_V_2_6_fu_1292_p0;
wire   [6:0] r_V_2_6_fu_1292_p1;
wire   [14:0] r_V_2_6_fu_1292_p2;
wire   [7:0] r_V_3_fu_1306_p0;
wire   [3:0] r_V_3_fu_1306_p1;
wire   [11:0] r_V_3_fu_1306_p2;
wire   [7:0] r_V_3_1_fu_1320_p0;
wire   [4:0] r_V_3_1_fu_1320_p1;
wire   [7:0] r_V_3_3_fu_1330_p0;
wire   [5:0] r_V_3_3_fu_1330_p1;
wire   [7:0] r_V_3_4_fu_1340_p0;
wire   [6:0] r_V_3_4_fu_1340_p1;
wire   [7:0] r_V_3_5_fu_1349_p0;
wire   [6:0] r_V_3_5_fu_1349_p1;
wire   [7:0] r_V_3_6_fu_1359_p0;
wire   [6:0] r_V_3_6_fu_1359_p1;
wire   [7:0] r_V_4_fu_1369_p0;
wire   [4:0] r_V_4_fu_1369_p1;
wire   [7:0] r_V_4_1_fu_1379_p0;
wire   [4:0] r_V_4_1_fu_1379_p1;
wire   [7:0] r_V_4_2_fu_1389_p0;
wire   [5:0] r_V_4_2_fu_1389_p1;
wire   [7:0] r_V_4_3_fu_1399_p0;
wire   [6:0] r_V_4_3_fu_1399_p1;
wire   [7:0] r_V_4_4_fu_1409_p0;
wire   [6:0] r_V_4_4_fu_1409_p1;
wire   [7:0] r_V_4_5_fu_1418_p0;
wire   [6:0] r_V_4_5_fu_1418_p1;
wire   [7:0] r_V_5_fu_1428_p0;
wire   [5:0] r_V_5_fu_1428_p1;
wire   [7:0] r_V_5_1_fu_1438_p0;
wire   [5:0] r_V_5_1_fu_1438_p1;
wire   [7:0] r_V_5_3_fu_1448_p0;
wire   [6:0] r_V_5_3_fu_1448_p1;
wire   [7:0] r_V_5_4_fu_1458_p0;
wire   [6:0] r_V_5_4_fu_1458_p1;
wire   [7:0] r_V_5_5_fu_1467_p0;
wire   [2:0] r_V_5_5_fu_1467_p1;
wire   [7:0] r_V_5_6_fu_1477_p0;
wire   [4:0] r_V_5_6_fu_1477_p1;
wire   [7:0] r_V_6_fu_1487_p0;
wire   [5:0] r_V_6_fu_1487_p1;
wire   [7:0] r_V_6_1_fu_1497_p0;
wire   [5:0] r_V_6_1_fu_1497_p1;
wire   [7:0] r_V_6_2_fu_1507_p0;
wire   [6:0] r_V_6_2_fu_1507_p1;
wire   [7:0] r_V_6_3_fu_1517_p0;
wire   [6:0] r_V_6_3_fu_1517_p1;
wire   [7:0] r_V_6_5_fu_1532_p0;
wire   [4:0] r_V_6_5_fu_1532_p1;
wire   [12:0] r_V_6_5_fu_1532_p2;
wire   [7:0] r_V_6_6_fu_1546_p0;
wire   [5:0] r_V_6_6_fu_1546_p1;
wire   [13:0] r_V_6_6_fu_1546_p2;
wire   [14:0] r_V_0_2_fu_1115_p2;
wire   [14:0] r_V_0_1_fu_1105_p2;
wire   [13:0] r_V_fu_1095_p2;
wire   [14:0] tmp5_fu_1556_p2;
wire   [7:0] tmp_66_fu_1562_p1;
wire   [7:0] tmp_67_fu_1566_p1;
wire   [13:0] r_V_0_6_fu_1144_p2;
wire   [13:0] r_V_0_5_fu_1134_p2;
wire   [12:0] r_V_0_4_fu_1125_p2;
wire   [13:0] tmp7_fu_1576_p2;
wire   [7:0] tmp_68_fu_1582_p1;
wire   [7:0] tmp_69_fu_1586_p1;
wire   [7:0] tmp4_cast_fu_1570_p2;
wire   [7:0] tmp6_cast_fu_1590_p2;
wire   [7:0] tmp_57_fu_1184_p1;
wire   [7:0] tmp_56_fu_1170_p1;
wire   [14:0] r_V_1_fu_1154_p2;
wire   [7:0] tmp_70_fu_1608_p1;
wire   [7:0] tmp10_fu_1602_p2;
wire   [13:0] r_V_1_5_fu_1211_p2;
wire   [13:0] r_V_1_4_fu_1202_p2;
wire   [12:0] r_V_1_3_fu_1192_p2;
wire   [13:0] tmp12_fu_1618_p2;
wire   [7:0] tmp_71_fu_1624_p1;
wire   [7:0] tmp_72_fu_1628_p1;
wire   [7:0] tmp9_cast_fu_1612_p2;
wire   [7:0] tmp11_cast_fu_1632_p2;
wire   [7:0] tmp3_fu_1596_p2;
wire   [7:0] tmp8_fu_1638_p2;
wire   [7:0] tmp_60_fu_1255_p1;
wire   [7:0] tmp_59_fu_1241_p1;
wire   [7:0] tmp_58_fu_1227_p1;
wire   [7:0] tmp16_fu_1650_p2;
wire   [13:0] r_V_2_4_fu_1273_p2;
wire   [13:0] r_V_2_3_fu_1263_p2;
wire   [13:0] tmp18_fu_1662_p2;
wire   [7:0] tmp_73_fu_1668_p2;
wire   [7:0] tmp_74_fu_1674_p1;
wire   [7:0] tmp15_fu_1656_p2;
wire   [7:0] tmp17_cast_fu_1678_p2;
wire   [7:0] tmp_62_fu_1312_p1;
wire   [7:0] tmp_61_fu_1298_p1;
wire   [14:0] r_V_2_5_fu_1282_p2;
wire   [7:0] tmp_75_fu_1696_p1;
wire   [7:0] tmp21_fu_1690_p2;
wire   [13:0] r_V_3_3_fu_1330_p2;
wire   [12:0] r_V_3_1_fu_1320_p2;
wire   [7:0] tmp_76_fu_1706_p1;
wire   [7:0] tmp_77_fu_1710_p2;
wire   [7:0] tmp_78_fu_1716_p1;
wire   [7:0] tmp_79_fu_1720_p2;
wire   [7:0] tmp20_cast_fu_1700_p2;
wire   [7:0] tmp22_cast_fu_1726_p2;
wire   [7:0] tmp14_fu_1684_p2;
wire   [7:0] tmp19_fu_1732_p2;
wire   [7:0] tmp2_fu_1644_p2;
wire   [7:0] tmp13_fu_1738_p2;
wire   [14:0] r_V_3_6_fu_1359_p2;
wire   [14:0] r_V_3_5_fu_1349_p2;
wire   [14:0] r_V_3_4_fu_1340_p2;
wire   [14:0] tmp28_fu_1750_p2;
wire   [14:0] tmp27_fu_1756_p2;
wire   [13:0] r_V_4_2_fu_1389_p2;
wire   [12:0] r_V_4_1_fu_1379_p2;
wire   [12:0] r_V_4_fu_1369_p2;
wire   [7:0] tmp_81_fu_1766_p1;
wire   [7:0] tmp_82_fu_1770_p1;
wire   [7:0] tmp_83_fu_1774_p1;
wire   [7:0] tmp_84_fu_1778_p2;
wire   [7:0] tmp_80_fu_1762_p1;
wire   [7:0] tmp29_cast_fu_1784_p2;
wire   [14:0] r_V_4_5_fu_1418_p2;
wire   [14:0] r_V_4_4_fu_1409_p2;
wire   [14:0] r_V_4_3_fu_1399_p2;
wire   [14:0] tmp33_fu_1796_p2;
wire   [14:0] tmp32_fu_1802_p2;
wire   [13:0] r_V_5_1_fu_1438_p2;
wire   [13:0] r_V_5_fu_1428_p2;
wire   [13:0] tmp35_fu_1812_p2;
wire   [7:0] tmp_86_fu_1818_p2;
wire   [7:0] tmp_87_fu_1824_p1;
wire   [7:0] tmp_85_fu_1808_p1;
wire   [7:0] tmp34_cast_fu_1828_p2;
wire   [7:0] tmp26_fu_1790_p2;
wire   [7:0] tmp31_fu_1834_p2;
wire   [14:0] r_V_5_4_fu_1458_p2;
wire   [14:0] r_V_5_3_fu_1448_p2;
wire   [14:0] tmp39_fu_1846_p2;
wire   [7:0] tmp_88_fu_1852_p2;
wire   [7:0] tmp_89_fu_1858_p1;
wire   [13:0] r_V_6_fu_1487_p2;
wire   [12:0] r_V_5_6_fu_1477_p2;
wire   [10:0] r_V_5_5_fu_1467_p2;
wire   [7:0] tmp_90_fu_1868_p1;
wire   [7:0] tmp_91_fu_1872_p1;
wire   [7:0] tmp_92_fu_1876_p1;
wire   [7:0] tmp_93_fu_1880_p2;
wire   [7:0] tmp38_cast_fu_1862_p2;
wire   [7:0] tmp40_cast_fu_1886_p2;
wire   [14:0] r_V_6_3_fu_1517_p2;
wire   [14:0] r_V_6_2_fu_1507_p2;
wire   [13:0] r_V_6_1_fu_1497_p2;
wire   [14:0] tmp44_fu_1898_p2;
wire   [7:0] tmp_94_fu_1904_p1;
wire   [7:0] tmp_95_fu_1908_p1;
wire   [7:0] tmp_64_fu_1538_p1;
wire   [7:0] tmp_63_fu_1523_p2;
wire   [7:0] tmp_65_fu_1552_p1;
wire   [7:0] tmp46_fu_1918_p2;
wire   [7:0] tmp47_fu_1924_p2;
wire   [7:0] tmp43_cast_fu_1912_p2;
wire   [7:0] tmp45_fu_1930_p2;
wire   [7:0] tmp37_fu_1892_p2;
wire   [7:0] tmp42_fu_1936_p2;
wire   [7:0] tmp25_fu_1840_p2;
wire   [7:0] tmp36_fu_1942_p2;
wire   [7:0] tmp24_fu_1948_p2;
wire   [7:0] tmp1_fu_1744_p2;
reg    ap_sig_cseq_ST_st5_fsm_2;
reg    ap_sig_1152;
reg   [2:0] ap_NS_fsm;
wire   [14:0] r_V_0_1_fu_1105_p00;
wire   [14:0] r_V_0_2_fu_1115_p00;
wire   [12:0] r_V_0_4_fu_1125_p00;
wire   [13:0] r_V_0_5_fu_1134_p00;
wire   [13:0] r_V_0_6_fu_1144_p00;
wire   [14:0] r_V_1_1_fu_1164_p00;
wire   [11:0] r_V_1_2_fu_1178_p00;
wire   [12:0] r_V_1_3_fu_1192_p00;
wire   [13:0] r_V_1_4_fu_1202_p00;
wire   [13:0] r_V_1_5_fu_1211_p00;
wire   [13:0] r_V_1_6_fu_1221_p00;
wire   [14:0] r_V_1_fu_1154_p00;
wire   [11:0] r_V_2_1_fu_1249_p00;
wire   [13:0] r_V_2_3_fu_1263_p00;
wire   [13:0] r_V_2_4_fu_1273_p00;
wire   [14:0] r_V_2_5_fu_1282_p00;
wire   [14:0] r_V_2_6_fu_1292_p00;
wire   [14:0] r_V_2_fu_1235_p00;
wire   [12:0] r_V_3_1_fu_1320_p00;
wire   [13:0] r_V_3_3_fu_1330_p00;
wire   [14:0] r_V_3_4_fu_1340_p00;
wire   [14:0] r_V_3_5_fu_1349_p00;
wire   [14:0] r_V_3_6_fu_1359_p00;
wire   [11:0] r_V_3_fu_1306_p00;
wire   [12:0] r_V_4_1_fu_1379_p00;
wire   [13:0] r_V_4_2_fu_1389_p00;
wire   [14:0] r_V_4_3_fu_1399_p00;
wire   [14:0] r_V_4_4_fu_1409_p00;
wire   [14:0] r_V_4_5_fu_1418_p00;
wire   [12:0] r_V_4_fu_1369_p00;
wire   [13:0] r_V_5_1_fu_1438_p00;
wire   [14:0] r_V_5_3_fu_1448_p00;
wire   [14:0] r_V_5_4_fu_1458_p00;
wire   [10:0] r_V_5_5_fu_1467_p00;
wire   [12:0] r_V_5_6_fu_1477_p00;
wire   [13:0] r_V_5_fu_1428_p00;
wire   [13:0] r_V_6_1_fu_1497_p00;
wire   [14:0] r_V_6_2_fu_1507_p00;
wire   [14:0] r_V_6_3_fu_1517_p00;
wire   [12:0] r_V_6_5_fu_1532_p00;
wire   [13:0] r_V_6_6_fu_1546_p00;
wire   [13:0] r_V_6_fu_1487_p00;
wire   [13:0] r_V_fu_1095_p00;
reg    ap_sig_1256;
reg    ap_sig_172;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'b1;
#0 window_V_0_6 = 8'b00000000;
#0 window_V_1_6 = 8'b00000000;
#0 window_V_2_6 = 8'b00000000;
#0 window_V_3_6 = 8'b00000000;
#0 window_V_4_6 = 8'b00000000;
#0 window_V_5_6 = 8'b00000000;
#0 window_V_6_6 = 8'b00000000;
#0 window_V_0_1 = 8'b00000000;
#0 window_V_0_2 = 8'b00000000;
#0 window_V_0_3 = 8'b00000000;
#0 window_V_0_4 = 8'b00000000;
#0 window_V_0_5 = 8'b00000000;
#0 window_V_1_1 = 8'b00000000;
#0 window_V_1_2 = 8'b00000000;
#0 window_V_1_3 = 8'b00000000;
#0 window_V_1_4 = 8'b00000000;
#0 window_V_1_5 = 8'b00000000;
#0 window_V_2_1 = 8'b00000000;
#0 window_V_2_2 = 8'b00000000;
#0 window_V_2_3 = 8'b00000000;
#0 window_V_2_4 = 8'b00000000;
#0 window_V_2_5 = 8'b00000000;
#0 window_V_3_1 = 8'b00000000;
#0 window_V_3_2 = 8'b00000000;
#0 window_V_3_3 = 8'b00000000;
#0 window_V_3_4 = 8'b00000000;
#0 window_V_3_5 = 8'b00000000;
#0 window_V_4_1 = 8'b00000000;
#0 window_V_4_2 = 8'b00000000;
#0 window_V_4_3 = 8'b00000000;
#0 window_V_4_4 = 8'b00000000;
#0 window_V_4_5 = 8'b00000000;
#0 window_V_5_1 = 8'b00000000;
#0 window_V_5_2 = 8'b00000000;
#0 window_V_5_3 = 8'b00000000;
#0 window_V_5_4 = 8'b00000000;
#0 window_V_5_5 = 8'b00000000;
#0 window_V_6_1 = 8'b00000000;
#0 window_V_6_2 = 8'b00000000;
#0 window_V_6_3 = 8'b00000000;
#0 window_V_6_4 = 8'b00000000;
#0 window_V_6_5 = 8'b00000000;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ioackin_out_img_V_TREADY = 1'b0;
end

convolution_filter_line_buffer_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_V_0_address0),
    .ce0(line_buffer_V_0_ce0),
    .q0(line_buffer_V_0_q0),
    .address1(line_buffer_V_0_addr_reg_2040),
    .ce1(line_buffer_V_0_ce1),
    .we1(line_buffer_V_0_we1),
    .d1(line_buffer_V_1_q0)
);

convolution_filter_line_buffer_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_V_1_address0),
    .ce0(line_buffer_V_1_ce0),
    .q0(line_buffer_V_1_q0),
    .address1(line_buffer_V_1_addr_reg_2046),
    .ce1(line_buffer_V_1_ce1),
    .we1(line_buffer_V_1_we1),
    .d1(line_buffer_V_2_q0)
);

convolution_filter_line_buffer_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_V_2_address0),
    .ce0(line_buffer_V_2_ce0),
    .q0(line_buffer_V_2_q0),
    .address1(line_buffer_V_2_addr_reg_2052),
    .ce1(line_buffer_V_2_ce1),
    .we1(line_buffer_V_2_we1),
    .d1(line_buffer_V_3_q0)
);

convolution_filter_line_buffer_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_V_3_address0),
    .ce0(line_buffer_V_3_ce0),
    .q0(line_buffer_V_3_q0),
    .address1(line_buffer_V_3_addr_reg_2058),
    .ce1(line_buffer_V_3_ce1),
    .we1(line_buffer_V_3_we1),
    .d1(line_buffer_V_4_q0)
);

convolution_filter_line_buffer_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_V_4_address0),
    .ce0(line_buffer_V_4_ce0),
    .q0(line_buffer_V_4_q0),
    .address1(line_buffer_V_4_addr_reg_2064),
    .ce1(line_buffer_V_4_ce1),
    .we1(line_buffer_V_4_we1),
    .d1(line_buffer_V_5_q0)
);

convolution_filter_line_buffer_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_V_5_address0),
    .ce0(line_buffer_V_5_ce0),
    .q0(line_buffer_V_5_q0),
    .address1(line_buffer_V_5_address1),
    .ce1(line_buffer_V_5_ce1),
    .we1(line_buffer_V_5_we1),
    .d1(in_temp_V_reg_2079)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U1(
    .din0(r_V_fu_1095_p0),
    .din1(r_V_fu_1095_p1),
    .dout(r_V_fu_1095_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U2(
    .din0(r_V_0_1_fu_1105_p0),
    .din1(r_V_0_1_fu_1105_p1),
    .dout(r_V_0_1_fu_1105_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U3(
    .din0(r_V_0_2_fu_1115_p0),
    .din1(r_V_0_2_fu_1115_p1),
    .dout(r_V_0_2_fu_1115_p2)
);

convolution_filter_mul_8ns_5ns_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
convolution_filter_mul_8ns_5ns_13_1_U4(
    .din0(r_V_0_4_fu_1125_p0),
    .din1(r_V_0_4_fu_1125_p1),
    .dout(r_V_0_4_fu_1125_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U5(
    .din0(r_V_0_5_fu_1134_p0),
    .din1(r_V_0_5_fu_1134_p1),
    .dout(r_V_0_5_fu_1134_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U6(
    .din0(r_V_0_6_fu_1144_p0),
    .din1(r_V_0_6_fu_1144_p1),
    .dout(r_V_0_6_fu_1144_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U7(
    .din0(r_V_1_fu_1154_p0),
    .din1(r_V_1_fu_1154_p1),
    .dout(r_V_1_fu_1154_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U8(
    .din0(r_V_1_1_fu_1164_p0),
    .din1(r_V_1_1_fu_1164_p1),
    .dout(r_V_1_1_fu_1164_p2)
);

convolution_filter_mul_8ns_4ns_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
convolution_filter_mul_8ns_4ns_12_1_U9(
    .din0(r_V_1_2_fu_1178_p0),
    .din1(r_V_1_2_fu_1178_p1),
    .dout(r_V_1_2_fu_1178_p2)
);

convolution_filter_mul_8ns_5ns_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
convolution_filter_mul_8ns_5ns_13_1_U10(
    .din0(r_V_1_3_fu_1192_p0),
    .din1(r_V_1_3_fu_1192_p1),
    .dout(r_V_1_3_fu_1192_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U11(
    .din0(r_V_1_4_fu_1202_p0),
    .din1(r_V_1_4_fu_1202_p1),
    .dout(r_V_1_4_fu_1202_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U12(
    .din0(r_V_1_5_fu_1211_p0),
    .din1(r_V_1_5_fu_1211_p1),
    .dout(r_V_1_5_fu_1211_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U13(
    .din0(r_V_1_6_fu_1221_p0),
    .din1(r_V_1_6_fu_1221_p1),
    .dout(r_V_1_6_fu_1221_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U14(
    .din0(r_V_2_fu_1235_p0),
    .din1(r_V_2_fu_1235_p1),
    .dout(r_V_2_fu_1235_p2)
);

convolution_filter_mul_8ns_4ns_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
convolution_filter_mul_8ns_4ns_12_1_U15(
    .din0(r_V_2_1_fu_1249_p0),
    .din1(r_V_2_1_fu_1249_p1),
    .dout(r_V_2_1_fu_1249_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U16(
    .din0(r_V_2_3_fu_1263_p0),
    .din1(r_V_2_3_fu_1263_p1),
    .dout(r_V_2_3_fu_1263_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U17(
    .din0(r_V_2_4_fu_1273_p0),
    .din1(r_V_2_4_fu_1273_p1),
    .dout(r_V_2_4_fu_1273_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U18(
    .din0(r_V_2_5_fu_1282_p0),
    .din1(r_V_2_5_fu_1282_p1),
    .dout(r_V_2_5_fu_1282_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U19(
    .din0(r_V_2_6_fu_1292_p0),
    .din1(r_V_2_6_fu_1292_p1),
    .dout(r_V_2_6_fu_1292_p2)
);

convolution_filter_mul_8ns_4ns_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
convolution_filter_mul_8ns_4ns_12_1_U20(
    .din0(r_V_3_fu_1306_p0),
    .din1(r_V_3_fu_1306_p1),
    .dout(r_V_3_fu_1306_p2)
);

convolution_filter_mul_8ns_5ns_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
convolution_filter_mul_8ns_5ns_13_1_U21(
    .din0(r_V_3_1_fu_1320_p0),
    .din1(r_V_3_1_fu_1320_p1),
    .dout(r_V_3_1_fu_1320_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U22(
    .din0(r_V_3_3_fu_1330_p0),
    .din1(r_V_3_3_fu_1330_p1),
    .dout(r_V_3_3_fu_1330_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U23(
    .din0(r_V_3_4_fu_1340_p0),
    .din1(r_V_3_4_fu_1340_p1),
    .dout(r_V_3_4_fu_1340_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U24(
    .din0(r_V_3_5_fu_1349_p0),
    .din1(r_V_3_5_fu_1349_p1),
    .dout(r_V_3_5_fu_1349_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U25(
    .din0(r_V_3_6_fu_1359_p0),
    .din1(r_V_3_6_fu_1359_p1),
    .dout(r_V_3_6_fu_1359_p2)
);

convolution_filter_mul_8ns_5ns_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
convolution_filter_mul_8ns_5ns_13_1_U26(
    .din0(r_V_4_fu_1369_p0),
    .din1(r_V_4_fu_1369_p1),
    .dout(r_V_4_fu_1369_p2)
);

convolution_filter_mul_8ns_5ns_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
convolution_filter_mul_8ns_5ns_13_1_U27(
    .din0(r_V_4_1_fu_1379_p0),
    .din1(r_V_4_1_fu_1379_p1),
    .dout(r_V_4_1_fu_1379_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U28(
    .din0(r_V_4_2_fu_1389_p0),
    .din1(r_V_4_2_fu_1389_p1),
    .dout(r_V_4_2_fu_1389_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U29(
    .din0(r_V_4_3_fu_1399_p0),
    .din1(r_V_4_3_fu_1399_p1),
    .dout(r_V_4_3_fu_1399_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U30(
    .din0(r_V_4_4_fu_1409_p0),
    .din1(r_V_4_4_fu_1409_p1),
    .dout(r_V_4_4_fu_1409_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U31(
    .din0(r_V_4_5_fu_1418_p0),
    .din1(r_V_4_5_fu_1418_p1),
    .dout(r_V_4_5_fu_1418_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U32(
    .din0(r_V_5_fu_1428_p0),
    .din1(r_V_5_fu_1428_p1),
    .dout(r_V_5_fu_1428_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U33(
    .din0(r_V_5_1_fu_1438_p0),
    .din1(r_V_5_1_fu_1438_p1),
    .dout(r_V_5_1_fu_1438_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U34(
    .din0(r_V_5_3_fu_1448_p0),
    .din1(r_V_5_3_fu_1448_p1),
    .dout(r_V_5_3_fu_1448_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U35(
    .din0(r_V_5_4_fu_1458_p0),
    .din1(r_V_5_4_fu_1458_p1),
    .dout(r_V_5_4_fu_1458_p2)
);

convolution_filter_mul_8ns_3ns_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 11 ))
convolution_filter_mul_8ns_3ns_11_1_U36(
    .din0(r_V_5_5_fu_1467_p0),
    .din1(r_V_5_5_fu_1467_p1),
    .dout(r_V_5_5_fu_1467_p2)
);

convolution_filter_mul_8ns_5ns_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
convolution_filter_mul_8ns_5ns_13_1_U37(
    .din0(r_V_5_6_fu_1477_p0),
    .din1(r_V_5_6_fu_1477_p1),
    .dout(r_V_5_6_fu_1477_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U38(
    .din0(r_V_6_fu_1487_p0),
    .din1(r_V_6_fu_1487_p1),
    .dout(r_V_6_fu_1487_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U39(
    .din0(r_V_6_1_fu_1497_p0),
    .din1(r_V_6_1_fu_1497_p1),
    .dout(r_V_6_1_fu_1497_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U40(
    .din0(r_V_6_2_fu_1507_p0),
    .din1(r_V_6_2_fu_1507_p1),
    .dout(r_V_6_2_fu_1507_p2)
);

convolution_filter_mul_8ns_7ns_15_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 15 ))
convolution_filter_mul_8ns_7ns_15_1_U41(
    .din0(r_V_6_3_fu_1517_p0),
    .din1(r_V_6_3_fu_1517_p1),
    .dout(r_V_6_3_fu_1517_p2)
);

convolution_filter_mul_8ns_5ns_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 13 ))
convolution_filter_mul_8ns_5ns_13_1_U42(
    .din0(r_V_6_5_fu_1532_p0),
    .din1(r_V_6_5_fu_1532_p1),
    .dout(r_V_6_5_fu_1532_p2)
);

convolution_filter_mul_8ns_6ns_14_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
convolution_filter_mul_8ns_6ns_14_1_U43(
    .din0(r_V_6_6_fu_1546_p0),
    .din1(r_V_6_6_fu_1546_p1),
    .dout(r_V_6_6_fu_1546_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_out_img_V_TREADY <= 1'b0;
    end else begin
        if (ap_sig_172) begin
            if (~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY)))) begin
                ap_reg_ioackin_out_img_V_TREADY <= 1'b0;
            end else if (ap_sig_1256) begin
                ap_reg_ioackin_out_img_V_TREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(exitcond_flatten_fu_506_p2 == 1'b0))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0)) | (~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(1'b1 == ap_reg_ppiten_pp0_it0)))) begin
            ap_reg_ppiten_pp0_it2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_506_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        col_reg_432 <= col_1_fu_626_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        col_reg_432 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == or_cond_reg_2075))) begin
        in_temp_V_1_fu_266 <= in_temp_V_reg_2079;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        in_temp_V_1_fu_266 <= window_V_6_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_506_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        indvar_flatten_reg_410 <= indvar_flatten_next_fu_512_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        indvar_flatten_reg_410 <= ap_const_lv19_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_506_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        row_reg_421 <= row_mid2_fu_578_p3;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        row_reg_421 <= ap_const_lv9_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        window_V_0_6_loc_1_fu_290 <= line_buffer_V_0_q0;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        window_V_0_6_loc_1_fu_290 <= window_V_0_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        window_V_1_6_loc_1_fu_286 <= line_buffer_V_1_q0;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        window_V_1_6_loc_1_fu_286 <= window_V_1_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        window_V_2_6_loc_1_fu_282 <= line_buffer_V_2_q0;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        window_V_2_6_loc_1_fu_282 <= window_V_2_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        window_V_3_6_loc_1_fu_278 <= line_buffer_V_3_q0;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        window_V_3_6_loc_1_fu_278 <= window_V_3_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        window_V_4_6_loc_1_fu_274 <= line_buffer_V_4_q0;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        window_V_4_6_loc_1_fu_274 <= window_V_4_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        window_V_5_6_loc_1_fu_270 <= line_buffer_V_5_q0;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        window_V_5_6_loc_1_fu_270 <= window_V_5_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        ap_reg_ppstg_exitcond_flatten_reg_2017_pp0_iter1 <= exitcond_flatten_reg_2017;
        ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1 <= or_cond1_reg_2085;
        exitcond_flatten_reg_2017 <= exitcond_flatten_fu_506_p2;
        in_temp_V_1_load_reg_2094 <= in_temp_V_1_fu_266;
        window_V_0_6_loc_1_load_reg_2130 <= window_V_0_6_loc_1_fu_290;
        window_V_1_6_loc_1_load_reg_2124 <= window_V_1_6_loc_1_fu_286;
        window_V_2_6_loc_1_load_reg_2118 <= window_V_2_6_loc_1_fu_282;
        window_V_3_6_loc_1_load_reg_2112 <= window_V_3_6_loc_1_fu_278;
        window_V_4_6_loc_1_load_reg_2106 <= window_V_4_6_loc_1_fu_274;
        window_V_5_6_loc_1_load_reg_2100 <= window_V_5_6_loc_1_fu_270;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_fu_506_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        col_mid2_reg_2026 <= col_mid2_fu_524_p3;
        or_cond1_reg_2085 <= or_cond1_fu_620_p2;
        or_cond_reg_2075 <= or_cond_fu_602_p2;
        tmp_4_reg_2036 <= tmp_4_fu_586_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_fu_506_p2 == 1'b0) & ~(1'b0 == or_cond_fu_602_p2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        in_temp_V_reg_2079 <= in_img_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_fu_506_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(1'b0 == tmp_4_fu_586_p2))) begin
        line_buffer_V_0_addr_reg_2040 <= tmp_6_fu_592_p1;
        line_buffer_V_1_addr_reg_2046 <= tmp_6_fu_592_p1;
        line_buffer_V_2_addr_reg_2052 <= tmp_6_fu_592_p1;
        line_buffer_V_3_addr_reg_2058 <= tmp_6_fu_592_p1;
        line_buffer_V_4_addr_reg_2064 <= tmp_6_fu_592_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_2017_pp0_iter1))) begin
        window_V_0_1 <= window_V_0_2;
        window_V_0_2 <= window_V_0_3;
        window_V_0_3 <= window_V_0_4;
        window_V_0_4 <= window_V_0_5;
        window_V_0_5 <= window_V_0_6_loc_1_load_reg_2130;
        window_V_1_1 <= window_V_1_2;
        window_V_1_2 <= window_V_1_3;
        window_V_1_3 <= window_V_1_4;
        window_V_1_4 <= window_V_1_5;
        window_V_1_5 <= window_V_1_6_loc_1_load_reg_2124;
        window_V_2_1 <= window_V_2_2;
        window_V_2_2 <= window_V_2_3;
        window_V_2_3 <= window_V_2_4;
        window_V_2_4 <= window_V_2_5;
        window_V_2_5 <= window_V_2_6_loc_1_load_reg_2118;
        window_V_3_1 <= window_V_3_2;
        window_V_3_2 <= window_V_3_3;
        window_V_3_3 <= window_V_3_4;
        window_V_3_4 <= window_V_3_5;
        window_V_3_5 <= window_V_3_6_loc_1_load_reg_2112;
        window_V_4_1 <= window_V_4_2;
        window_V_4_2 <= window_V_4_3;
        window_V_4_3 <= window_V_4_4;
        window_V_4_4 <= window_V_4_5;
        window_V_4_5 <= window_V_4_6_loc_1_load_reg_2106;
        window_V_5_1 <= window_V_5_2;
        window_V_5_2 <= window_V_5_3;
        window_V_5_3 <= window_V_5_4;
        window_V_5_4 <= window_V_5_5;
        window_V_5_5 <= window_V_5_6_loc_1_load_reg_2100;
        window_V_6_1 <= window_V_6_2;
        window_V_6_2 <= window_V_6_3;
        window_V_6_3 <= window_V_6_4;
        window_V_6_4 <= window_V_6_5;
        window_V_6_5 <= in_temp_V_1_load_reg_2094;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        window_V_0_6 <= line_buffer_V_0_q0;
        window_V_1_6 <= line_buffer_V_1_q0;
        window_V_2_6 <= line_buffer_V_2_q0;
        window_V_3_6 <= line_buffer_V_3_q0;
        window_V_4_6 <= line_buffer_V_4_q0;
        window_V_5_6 <= line_buffer_V_5_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_506_p2 == 1'b0) & ~(1'b0 == or_cond_fu_602_p2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        window_V_6_6 <= in_img_V_TDATA;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_149) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_20) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1152) begin
        ap_sig_cseq_ST_st5_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_out_img_V_TREADY)) begin
        ap_sig_ioackin_out_img_V_TREADY = out_img_V_TREADY;
    end else begin
        ap_sig_ioackin_out_img_V_TREADY = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_506_p2 == 1'b0) & ~(1'b0 == or_cond_fu_602_p2))) begin
        in_img_V_TDATA_blk_n = in_img_V_TVALID;
    end else begin
        in_img_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_506_p2 == 1'b0) & ~(1'b0 == or_cond_fu_602_p2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        in_img_V_TREADY = 1'b1;
    end else begin
        in_img_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_0_ce0 = 1'b1;
    end else begin
        line_buffer_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_0_ce1 = 1'b1;
    end else begin
        line_buffer_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        line_buffer_V_0_we1 = 1'b1;
    end else begin
        line_buffer_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_1_ce0 = 1'b1;
    end else begin
        line_buffer_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_1_ce1 = 1'b1;
    end else begin
        line_buffer_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        line_buffer_V_1_we1 = 1'b1;
    end else begin
        line_buffer_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_2_ce0 = 1'b1;
    end else begin
        line_buffer_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_2_ce1 = 1'b1;
    end else begin
        line_buffer_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        line_buffer_V_2_we1 = 1'b1;
    end else begin
        line_buffer_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_3_ce0 = 1'b1;
    end else begin
        line_buffer_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_3_ce1 = 1'b1;
    end else begin
        line_buffer_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        line_buffer_V_3_we1 = 1'b1;
    end else begin
        line_buffer_V_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_4_ce0 = 1'b1;
    end else begin
        line_buffer_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_4_ce1 = 1'b1;
    end else begin
        line_buffer_V_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == tmp_4_reg_2036))) begin
        line_buffer_V_4_we1 = 1'b1;
    end else begin
        line_buffer_V_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_5_ce0 = 1'b1;
    end else begin
        line_buffer_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_5_ce1 = 1'b1;
    end else begin
        line_buffer_V_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & (1'b0 == exitcond_flatten_reg_2017) & ~(1'b0 == or_cond_reg_2075))) begin
        line_buffer_V_5_we1 = 1'b1;
    end else begin
        line_buffer_V_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1))) begin
        out_img_V_TDATA_blk_n = out_img_V_TREADY;
    end else begin
        out_img_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) & (1'b0 == ap_reg_ioackin_out_img_V_TREADY))) begin
        out_img_V_TVALID = 1'b1;
    end else begin
        out_img_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : begin
            if (~((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(1'b1 == ap_reg_ppiten_pp0_it0))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(1'b1 == ap_reg_ppiten_pp0_it0))) begin
                ap_NS_fsm = ap_ST_st5_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end
        end
        ap_ST_st5_fsm_2 : begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

always @ (*) begin
    ap_sig_1152 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_1256 = (~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_181) & (1'b1 == out_img_V_TREADY));
end

always @ (*) begin
    ap_sig_149 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_172 = ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_2085_pp0_iter1));
end

always @ (*) begin
    ap_sig_181 = ((exitcond_flatten_fu_506_p2 == 1'b0) & ~(1'b0 == or_cond_fu_602_p2) & (in_img_V_TVALID == 1'b0));
end

always @ (*) begin
    ap_sig_20 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

assign col_1_fu_626_p2 = (col_mid2_fu_524_p3 + ap_const_lv10_1);

assign col_mid2_fu_524_p3 = ((exitcond_fu_518_p2[0:0] === 1'b1) ? ap_const_lv10_0 : col_reg_432);

assign exitcond_flatten_fu_506_p2 = ((indvar_flatten_reg_410 == ap_const_lv19_4BD29) ? 1'b1 : 1'b0);

assign exitcond_fu_518_p2 = ((col_reg_432 == ap_const_lv10_283) ? 1'b1 : 1'b0);

assign indvar_flatten_next_fu_512_p2 = (indvar_flatten_reg_410 + ap_const_lv19_1);

assign line_buffer_V_0_address0 = tmp_6_fu_592_p1;

assign line_buffer_V_1_address0 = tmp_6_fu_592_p1;

assign line_buffer_V_2_address0 = tmp_6_fu_592_p1;

assign line_buffer_V_3_address0 = tmp_6_fu_592_p1;

assign line_buffer_V_4_address0 = tmp_6_fu_592_p1;

assign line_buffer_V_5_address0 = tmp_6_fu_592_p1;

assign line_buffer_V_5_address1 = tmp_8_fu_719_p1;

assign or_cond1_fu_620_p2 = (tmp_2_mid2_fu_570_p3 & tmp_9_fu_614_p2);

assign or_cond_fu_602_p2 = (tmp_4_fu_586_p2 & tmp_mid2_fu_550_p3);

assign out_img_V_TDATA = (tmp24_fu_1948_p2 + tmp1_fu_1744_p2);

assign r_V_0_1_fu_1105_p0 = r_V_0_1_fu_1105_p00;

assign r_V_0_1_fu_1105_p00 = window_V_0_2;

assign r_V_0_1_fu_1105_p1 = ap_const_lv15_27;

assign r_V_0_2_fu_1115_p0 = r_V_0_2_fu_1115_p00;

assign r_V_0_2_fu_1115_p00 = window_V_0_3;

assign r_V_0_2_fu_1115_p1 = ap_const_lv15_30;

assign r_V_0_4_fu_1125_p0 = r_V_0_4_fu_1125_p00;

assign r_V_0_4_fu_1125_p00 = window_V_0_5;

assign r_V_0_4_fu_1125_p1 = ap_const_lv13_A;

assign r_V_0_5_fu_1134_p0 = r_V_0_5_fu_1134_p00;

assign r_V_0_5_fu_1134_p00 = window_V_0_6_loc_1_load_reg_2130;

assign r_V_0_5_fu_1134_p1 = ap_const_lv14_13;

assign r_V_0_6_fu_1144_p0 = r_V_0_6_fu_1144_p00;

assign r_V_0_6_fu_1144_p00 = window_V_0_6_loc_1_fu_290;

assign r_V_0_6_fu_1144_p1 = ap_const_lv14_1C;

assign r_V_1_1_fu_1164_p0 = r_V_1_1_fu_1164_p00;

assign r_V_1_1_fu_1164_p00 = window_V_1_2;

assign r_V_1_1_fu_1164_p1 = ap_const_lv15_2F;

assign r_V_1_2_fu_1178_p0 = r_V_1_2_fu_1178_p00;

assign r_V_1_2_fu_1178_p00 = window_V_1_3;

assign r_V_1_2_fu_1178_p1 = ap_const_lv12_7;

assign r_V_1_3_fu_1192_p0 = r_V_1_3_fu_1192_p00;

assign r_V_1_3_fu_1192_p00 = window_V_1_4;

assign r_V_1_3_fu_1192_p1 = ap_const_lv13_9;

assign r_V_1_4_fu_1202_p0 = r_V_1_4_fu_1202_p00;

assign r_V_1_4_fu_1202_p00 = window_V_1_5;

assign r_V_1_4_fu_1202_p1 = ap_const_lv14_12;

assign r_V_1_5_fu_1211_p0 = r_V_1_5_fu_1211_p00;

assign r_V_1_5_fu_1211_p00 = window_V_1_6_loc_1_load_reg_2124;

assign r_V_1_5_fu_1211_p1 = ap_const_lv14_1B;

assign r_V_1_6_fu_1221_p0 = r_V_1_6_fu_1221_p00;

assign r_V_1_6_fu_1221_p00 = window_V_1_6_loc_1_fu_286;

assign r_V_1_6_fu_1221_p1 = ap_const_lv14_1D;

assign r_V_1_fu_1154_p0 = r_V_1_fu_1154_p00;

assign r_V_1_fu_1154_p00 = window_V_1_1;

assign r_V_1_fu_1154_p1 = ap_const_lv15_26;

assign r_V_2_1_fu_1249_p0 = r_V_2_1_fu_1249_p00;

assign r_V_2_1_fu_1249_p00 = window_V_2_2;

assign r_V_2_1_fu_1249_p1 = ap_const_lv12_6;

assign r_V_2_3_fu_1263_p0 = r_V_2_3_fu_1263_p00;

assign r_V_2_3_fu_1263_p00 = window_V_2_4;

assign r_V_2_3_fu_1263_p1 = ap_const_lv14_11;

assign r_V_2_4_fu_1273_p0 = r_V_2_4_fu_1273_p00;

assign r_V_2_4_fu_1273_p00 = window_V_2_5;

assign r_V_2_4_fu_1273_p1 = ap_const_lv14_1A;

assign r_V_2_5_fu_1282_p0 = r_V_2_5_fu_1282_p00;

assign r_V_2_5_fu_1282_p00 = window_V_2_6_loc_1_load_reg_2118;

assign r_V_2_5_fu_1282_p1 = ap_const_lv15_23;

assign r_V_2_6_fu_1292_p0 = r_V_2_6_fu_1292_p00;

assign r_V_2_6_fu_1292_p00 = window_V_2_6_loc_1_fu_282;

assign r_V_2_6_fu_1292_p1 = ap_const_lv15_25;

assign r_V_2_fu_1235_p0 = r_V_2_fu_1235_p00;

assign r_V_2_fu_1235_p00 = window_V_2_1;

assign r_V_2_fu_1235_p1 = ap_const_lv15_2E;

assign r_V_3_1_fu_1320_p0 = r_V_3_1_fu_1320_p00;

assign r_V_3_1_fu_1320_p00 = window_V_3_2;

assign r_V_3_1_fu_1320_p1 = ap_const_lv13_E;

assign r_V_3_3_fu_1330_p0 = r_V_3_3_fu_1330_p00;

assign r_V_3_3_fu_1330_p00 = window_V_3_4;

assign r_V_3_3_fu_1330_p1 = ap_const_lv14_19;

assign r_V_3_4_fu_1340_p0 = r_V_3_4_fu_1340_p00;

assign r_V_3_4_fu_1340_p00 = window_V_3_5;

assign r_V_3_4_fu_1340_p1 = ap_const_lv15_22;

assign r_V_3_5_fu_1349_p0 = r_V_3_5_fu_1349_p00;

assign r_V_3_5_fu_1349_p00 = window_V_3_6_loc_1_load_reg_2112;

assign r_V_3_5_fu_1349_p1 = ap_const_lv15_24;

assign r_V_3_6_fu_1359_p0 = r_V_3_6_fu_1359_p00;

assign r_V_3_6_fu_1359_p00 = window_V_3_6_loc_1_fu_278;

assign r_V_3_6_fu_1359_p1 = ap_const_lv15_2D;

assign r_V_3_fu_1306_p0 = r_V_3_fu_1306_p00;

assign r_V_3_fu_1306_p00 = window_V_3_1;

assign r_V_3_fu_1306_p1 = ap_const_lv12_5;

assign r_V_4_1_fu_1379_p0 = r_V_4_1_fu_1379_p00;

assign r_V_4_1_fu_1379_p00 = window_V_4_2;

assign r_V_4_1_fu_1379_p1 = ap_const_lv13_F;

assign r_V_4_2_fu_1389_p0 = r_V_4_2_fu_1389_p00;

assign r_V_4_2_fu_1389_p00 = window_V_4_3;

assign r_V_4_2_fu_1389_p1 = ap_const_lv14_18;

assign r_V_4_3_fu_1399_p0 = r_V_4_3_fu_1399_p00;

assign r_V_4_3_fu_1399_p00 = window_V_4_4;

assign r_V_4_3_fu_1399_p1 = ap_const_lv15_21;

assign r_V_4_4_fu_1409_p0 = r_V_4_4_fu_1409_p00;

assign r_V_4_4_fu_1409_p00 = window_V_4_5;

assign r_V_4_4_fu_1409_p1 = ap_const_lv15_2A;

assign r_V_4_5_fu_1418_p0 = r_V_4_5_fu_1418_p00;

assign r_V_4_5_fu_1418_p00 = window_V_4_6_loc_1_load_reg_2106;

assign r_V_4_5_fu_1418_p1 = ap_const_lv15_2C;

assign r_V_4_fu_1369_p0 = r_V_4_fu_1369_p00;

assign r_V_4_fu_1369_p00 = window_V_4_1;

assign r_V_4_fu_1369_p1 = ap_const_lv13_D;

assign r_V_5_1_fu_1438_p0 = r_V_5_1_fu_1438_p00;

assign r_V_5_1_fu_1438_p00 = window_V_5_2;

assign r_V_5_1_fu_1438_p1 = ap_const_lv14_17;

assign r_V_5_3_fu_1448_p0 = r_V_5_3_fu_1448_p00;

assign r_V_5_3_fu_1448_p00 = window_V_5_4;

assign r_V_5_3_fu_1448_p1 = ap_const_lv15_29;

assign r_V_5_4_fu_1458_p0 = r_V_5_4_fu_1458_p00;

assign r_V_5_4_fu_1458_p00 = window_V_5_5;

assign r_V_5_4_fu_1458_p1 = ap_const_lv15_2B;

assign r_V_5_5_fu_1467_p0 = r_V_5_5_fu_1467_p00;

assign r_V_5_5_fu_1467_p00 = window_V_5_6_loc_1_load_reg_2100;

assign r_V_5_5_fu_1467_p1 = ap_const_lv11_3;

assign r_V_5_6_fu_1477_p0 = r_V_5_6_fu_1477_p00;

assign r_V_5_6_fu_1477_p00 = window_V_5_6_loc_1_fu_270;

assign r_V_5_6_fu_1477_p1 = ap_const_lv13_C;

assign r_V_5_fu_1428_p0 = r_V_5_fu_1428_p00;

assign r_V_5_fu_1428_p00 = window_V_5_1;

assign r_V_5_fu_1428_p1 = ap_const_lv14_15;

assign r_V_6_1_fu_1497_p0 = r_V_6_1_fu_1497_p00;

assign r_V_6_1_fu_1497_p00 = window_V_6_2;

assign r_V_6_1_fu_1497_p1 = ap_const_lv14_1F;

assign r_V_6_2_fu_1507_p0 = r_V_6_2_fu_1507_p00;

assign r_V_6_2_fu_1507_p00 = window_V_6_3;

assign r_V_6_2_fu_1507_p1 = ap_const_lv15_28;

assign r_V_6_3_fu_1517_p0 = r_V_6_3_fu_1517_p00;

assign r_V_6_3_fu_1517_p00 = window_V_6_4;

assign r_V_6_3_fu_1517_p1 = ap_const_lv15_31;

assign r_V_6_5_fu_1532_p0 = r_V_6_5_fu_1532_p00;

assign r_V_6_5_fu_1532_p00 = in_temp_V_1_load_reg_2094;

assign r_V_6_5_fu_1532_p1 = ap_const_lv13_B;

assign r_V_6_6_fu_1546_p0 = r_V_6_6_fu_1546_p00;

assign r_V_6_6_fu_1546_p00 = in_temp_V_1_fu_266;

assign r_V_6_6_fu_1546_p1 = ap_const_lv14_14;

assign r_V_6_fu_1487_p0 = r_V_6_fu_1487_p00;

assign r_V_6_fu_1487_p00 = window_V_6_1;

assign r_V_6_fu_1487_p1 = ap_const_lv14_16;

assign r_V_fu_1095_p0 = r_V_fu_1095_p00;

assign r_V_fu_1095_p00 = window_V_0_1;

assign r_V_fu_1095_p1 = ap_const_lv14_1E;

assign row_mid2_fu_578_p3 = ((exitcond_fu_518_p2[0:0] === 1'b1) ? row_s_fu_532_p2 : row_reg_421);

assign row_s_fu_532_p2 = (row_reg_421 + ap_const_lv9_1);

assign tmp10_fu_1602_p2 = (tmp_57_fu_1184_p1 + tmp_56_fu_1170_p1);

assign tmp11_cast_fu_1632_p2 = (tmp_71_fu_1624_p1 + tmp_72_fu_1628_p1);

assign tmp12_fu_1618_p2 = (r_V_1_5_fu_1211_p2 + r_V_1_4_fu_1202_p2);

assign tmp13_fu_1738_p2 = (tmp14_fu_1684_p2 + tmp19_fu_1732_p2);

assign tmp14_fu_1684_p2 = (tmp15_fu_1656_p2 + tmp17_cast_fu_1678_p2);

assign tmp15_fu_1656_p2 = (tmp_58_fu_1227_p1 + tmp16_fu_1650_p2);

assign tmp16_fu_1650_p2 = (tmp_60_fu_1255_p1 + tmp_59_fu_1241_p1);

assign tmp17_cast_fu_1678_p2 = (tmp_73_fu_1668_p2 + tmp_74_fu_1674_p1);

assign tmp18_fu_1662_p2 = (r_V_2_4_fu_1273_p2 + r_V_2_3_fu_1263_p2);

assign tmp19_fu_1732_p2 = (tmp20_cast_fu_1700_p2 + tmp22_cast_fu_1726_p2);

assign tmp1_fu_1744_p2 = (tmp2_fu_1644_p2 + tmp13_fu_1738_p2);

assign tmp20_cast_fu_1700_p2 = (tmp_75_fu_1696_p1 + tmp21_fu_1690_p2);

assign tmp21_fu_1690_p2 = (tmp_62_fu_1312_p1 + tmp_61_fu_1298_p1);

assign tmp22_cast_fu_1726_p2 = (tmp_78_fu_1716_p1 + tmp_79_fu_1720_p2);

assign tmp24_fu_1948_p2 = (tmp25_fu_1840_p2 + tmp36_fu_1942_p2);

assign tmp25_fu_1840_p2 = (tmp26_fu_1790_p2 + tmp31_fu_1834_p2);

assign tmp26_fu_1790_p2 = (tmp_80_fu_1762_p1 + tmp29_cast_fu_1784_p2);

assign tmp27_fu_1756_p2 = (r_V_3_4_fu_1340_p2 + tmp28_fu_1750_p2);

assign tmp28_fu_1750_p2 = (r_V_3_6_fu_1359_p2 + r_V_3_5_fu_1349_p2);

assign tmp29_cast_fu_1784_p2 = (tmp_83_fu_1774_p1 + tmp_84_fu_1778_p2);

assign tmp2_fu_1644_p2 = (tmp3_fu_1596_p2 + tmp8_fu_1638_p2);

assign tmp31_fu_1834_p2 = (tmp_85_fu_1808_p1 + tmp34_cast_fu_1828_p2);

assign tmp32_fu_1802_p2 = (r_V_4_3_fu_1399_p2 + tmp33_fu_1796_p2);

assign tmp33_fu_1796_p2 = (r_V_4_5_fu_1418_p2 + r_V_4_4_fu_1409_p2);

assign tmp34_cast_fu_1828_p2 = (tmp_86_fu_1818_p2 + tmp_87_fu_1824_p1);

assign tmp35_fu_1812_p2 = (r_V_5_1_fu_1438_p2 + r_V_5_fu_1428_p2);

assign tmp36_fu_1942_p2 = (tmp37_fu_1892_p2 + tmp42_fu_1936_p2);

assign tmp37_fu_1892_p2 = (tmp38_cast_fu_1862_p2 + tmp40_cast_fu_1886_p2);

assign tmp38_cast_fu_1862_p2 = (tmp_88_fu_1852_p2 + tmp_89_fu_1858_p1);

assign tmp39_fu_1846_p2 = (r_V_5_4_fu_1458_p2 + r_V_5_3_fu_1448_p2);

assign tmp3_fu_1596_p2 = (tmp4_cast_fu_1570_p2 + tmp6_cast_fu_1590_p2);

assign tmp40_cast_fu_1886_p2 = (tmp_92_fu_1876_p1 + tmp_93_fu_1880_p2);

assign tmp42_fu_1936_p2 = (tmp43_cast_fu_1912_p2 + tmp45_fu_1930_p2);

assign tmp43_cast_fu_1912_p2 = (tmp_94_fu_1904_p1 + tmp_95_fu_1908_p1);

assign tmp44_fu_1898_p2 = (r_V_6_3_fu_1517_p2 + r_V_6_2_fu_1507_p2);

assign tmp45_fu_1930_p2 = (tmp46_fu_1918_p2 + tmp47_fu_1924_p2);

assign tmp46_fu_1918_p2 = (tmp_64_fu_1538_p1 + tmp_63_fu_1523_p2);

assign tmp47_fu_1924_p2 = (window_V_0_4 + tmp_65_fu_1552_p1);

assign tmp4_cast_fu_1570_p2 = (tmp_66_fu_1562_p1 + tmp_67_fu_1566_p1);

assign tmp5_fu_1556_p2 = (r_V_0_2_fu_1115_p2 + r_V_0_1_fu_1105_p2);

assign tmp6_cast_fu_1590_p2 = (tmp_68_fu_1582_p1 + tmp_69_fu_1586_p1);

assign tmp7_fu_1576_p2 = (r_V_0_6_fu_1144_p2 + r_V_0_5_fu_1134_p2);

assign tmp8_fu_1638_p2 = (tmp9_cast_fu_1612_p2 + tmp11_cast_fu_1632_p2);

assign tmp9_cast_fu_1612_p2 = (tmp_70_fu_1608_p1 + tmp10_fu_1602_p2);

assign tmp_2_fu_564_p2 = ((row_reg_421 > ap_const_lv9_2) ? 1'b1 : 1'b0);

assign tmp_2_mid1_fu_558_p2 = ((row_s_fu_532_p2 > ap_const_lv9_2) ? 1'b1 : 1'b0);

assign tmp_2_mid2_fu_570_p3 = ((exitcond_fu_518_p2[0:0] === 1'b1) ? tmp_2_mid1_fu_558_p2 : tmp_2_fu_564_p2);

assign tmp_4_fu_586_p2 = ((col_mid2_fu_524_p3 < ap_const_lv10_280) ? 1'b1 : 1'b0);

assign tmp_56_fu_1170_p1 = r_V_1_1_fu_1164_p2[7:0];

assign tmp_57_fu_1184_p1 = r_V_1_2_fu_1178_p2[7:0];

assign tmp_58_fu_1227_p1 = r_V_1_6_fu_1221_p2[7:0];

assign tmp_59_fu_1241_p1 = r_V_2_fu_1235_p2[7:0];

assign tmp_60_fu_1255_p1 = r_V_2_1_fu_1249_p2[7:0];

assign tmp_61_fu_1298_p1 = r_V_2_6_fu_1292_p2[7:0];

assign tmp_62_fu_1312_p1 = r_V_3_fu_1306_p2[7:0];

assign tmp_63_fu_1523_p2 = window_V_6_5 << ap_const_lv8_1;

assign tmp_64_fu_1538_p1 = r_V_6_5_fu_1532_p2[7:0];

assign tmp_65_fu_1552_p1 = r_V_6_6_fu_1546_p2[7:0];

assign tmp_66_fu_1562_p1 = r_V_fu_1095_p2[7:0];

assign tmp_67_fu_1566_p1 = tmp5_fu_1556_p2[7:0];

assign tmp_68_fu_1582_p1 = r_V_0_4_fu_1125_p2[7:0];

assign tmp_69_fu_1586_p1 = tmp7_fu_1576_p2[7:0];

assign tmp_6_fu_592_p1 = col_mid2_fu_524_p3;

assign tmp_70_fu_1608_p1 = r_V_1_fu_1154_p2[7:0];

assign tmp_71_fu_1624_p1 = r_V_1_3_fu_1192_p2[7:0];

assign tmp_72_fu_1628_p1 = tmp12_fu_1618_p2[7:0];

assign tmp_73_fu_1668_p2 = window_V_2_3 << ap_const_lv8_3;

assign tmp_74_fu_1674_p1 = tmp18_fu_1662_p2[7:0];

assign tmp_75_fu_1696_p1 = r_V_2_5_fu_1282_p2[7:0];

assign tmp_76_fu_1706_p1 = r_V_3_3_fu_1330_p2[7:0];

assign tmp_77_fu_1710_p2 = window_V_3_3 << ap_const_lv8_4;

assign tmp_78_fu_1716_p1 = r_V_3_1_fu_1320_p2[7:0];

assign tmp_79_fu_1720_p2 = (tmp_76_fu_1706_p1 + tmp_77_fu_1710_p2);

assign tmp_80_fu_1762_p1 = tmp27_fu_1756_p2[7:0];

assign tmp_81_fu_1766_p1 = r_V_4_2_fu_1389_p2[7:0];

assign tmp_82_fu_1770_p1 = r_V_4_1_fu_1379_p2[7:0];

assign tmp_83_fu_1774_p1 = r_V_4_fu_1369_p2[7:0];

assign tmp_84_fu_1778_p2 = (tmp_81_fu_1766_p1 + tmp_82_fu_1770_p1);

assign tmp_85_fu_1808_p1 = tmp32_fu_1802_p2[7:0];

assign tmp_86_fu_1818_p2 = window_V_4_6_loc_1_fu_274 << ap_const_lv8_2;

assign tmp_87_fu_1824_p1 = tmp35_fu_1812_p2[7:0];

assign tmp_88_fu_1852_p2 = window_V_5_3 << ap_const_lv8_5;

assign tmp_89_fu_1858_p1 = tmp39_fu_1846_p2[7:0];

assign tmp_8_fu_719_p1 = col_mid2_reg_2026;

assign tmp_90_fu_1868_p1 = r_V_6_fu_1487_p2[7:0];

assign tmp_91_fu_1872_p1 = r_V_5_6_fu_1477_p2[7:0];

assign tmp_92_fu_1876_p1 = r_V_5_5_fu_1467_p2[7:0];

assign tmp_93_fu_1880_p2 = (tmp_90_fu_1868_p1 + tmp_91_fu_1872_p1);

assign tmp_94_fu_1904_p1 = r_V_6_1_fu_1497_p2[7:0];

assign tmp_95_fu_1908_p1 = tmp44_fu_1898_p2[7:0];

assign tmp_9_fu_614_p2 = ((col_mid2_fu_524_p3 > ap_const_lv10_2) ? 1'b1 : 1'b0);

assign tmp_fu_544_p2 = ((row_reg_421 < ap_const_lv9_1E0) ? 1'b1 : 1'b0);

assign tmp_mid1_fu_538_p2 = ((row_s_fu_532_p2 < ap_const_lv9_1E0) ? 1'b1 : 1'b0);

assign tmp_mid2_fu_550_p3 = ((exitcond_fu_518_p2[0:0] === 1'b1) ? tmp_mid1_fu_538_p2 : tmp_fu_544_p2);

endmodule //convolution_filter
