// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sep_convolution_filter,hls_ip_2016_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=41.666668,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=34.940000,HLS_SYN_LAT=308324,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=6,HLS_SYN_FF=135,HLS_SYN_LUT=275}" *)

module sep_convolution_filter (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_img_V_TDATA,
        in_img_V_TVALID,
        in_img_V_TREADY,
        out_img_V_TDATA,
        out_img_V_TVALID,
        out_img_V_TREADY
);

parameter    ap_ST_st1_fsm_0 = 3'b1;
parameter    ap_ST_pp0_stg0_fsm_1 = 3'b10;
parameter    ap_ST_st5_fsm_2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv17_0 = 17'b00000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv19_0 = 19'b0000000000000000000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv19_4B461 = 19'b1001011010001100001;
parameter    ap_const_lv19_1 = 19'b1;
parameter    ap_const_lv10_281 = 10'b1010000001;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv9_1E0 = 9'b111100000;
parameter    ap_const_lv10_280 = 10'b1010000000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv48_1020409 = 48'b1000000100000010000001001;
parameter    ap_const_lv48_0 = 48'b000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_26 = 32'b100110;
parameter    ap_const_lv8_3F = 8'b111111;
parameter    ap_const_lv24_47 = 24'b1000111;
parameter    ap_const_lv23_7FFFEA = 23'b11111111111111111101010;
parameter    ap_const_lv16_FF8E = 16'b1111111110001110;
parameter    ap_const_lv16_43 = 16'b1000011;
parameter    ap_const_lv32_2 = 32'b10;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_img_V_TDATA;
input   in_img_V_TVALID;
output   in_img_V_TREADY;
output  [7:0] out_img_V_TDATA;
output   out_img_V_TVALID;
input   out_img_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_img_V_TREADY;
reg out_img_V_TVALID;

reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_20;
wire   [9:0] line_buffer_V_0_address0;
reg    line_buffer_V_0_ce0;
wire   [7:0] line_buffer_V_0_q0;
reg    line_buffer_V_0_ce1;
reg    line_buffer_V_0_we1;
reg   [7:0] window_V_0;
wire   [9:0] line_buffer_V_1_address0;
reg    line_buffer_V_1_ce0;
wire   [7:0] line_buffer_V_1_q0;
wire   [9:0] line_buffer_V_1_address1;
reg    line_buffer_V_1_ce1;
reg    line_buffer_V_1_we1;
reg   [7:0] window_V_1;
reg   [7:0] window_V_2;
reg   [16:0] convolution_buffer_V_1;
reg  signed [16:0] convolution_buffer_V_2;
reg    in_img_V_TDATA_blk_n;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_1;
reg    ap_sig_69;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it2;
wire   [0:0] exitcond_flatten_fu_203_p2;
wire   [0:0] or_cond_fu_295_p2;
reg    out_img_V_TDATA_blk_n;
reg   [0:0] or_cond1_reg_619;
reg   [0:0] ap_reg_ppstg_or_cond1_reg_619_pp0_iter1;
reg   [18:0] indvar_flatten_reg_170;
reg   [8:0] row_reg_181;
reg   [9:0] col_reg_192;
reg    ap_sig_101;
reg    ap_sig_ioackin_out_img_V_TREADY;
wire   [18:0] indvar_flatten_next_fu_209_p2;
wire   [9:0] col_mid2_fu_221_p3;
reg   [9:0] col_mid2_reg_584;
wire   [8:0] row_mid2_fu_275_p3;
wire   [0:0] tmp_4_fu_283_p2;
reg   [0:0] tmp_4_reg_594;
reg   [9:0] line_buffer_V_0_addr_reg_598;
reg   [0:0] or_cond_reg_609;
reg   [7:0] in_temp_V_reg_613;
wire   [0:0] or_cond1_fu_307_p2;
wire   [9:0] col_1_fu_313_p2;
wire   [63:0] tmp_5_fu_289_p1;
wire   [63:0] tmp_8_fu_336_p1;
wire  signed [16:0] grp_fu_556_p3;
reg    ap_reg_ioackin_out_img_V_TREADY;
wire   [0:0] exitcond_fu_215_p2;
wire   [8:0] row_s_fu_229_p2;
wire   [0:0] tmp_mid1_fu_235_p2;
wire   [0:0] tmp6_fu_241_p2;
wire   [0:0] tmp_2_mid1_fu_255_p2;
wire   [0:0] tmp_s_fu_261_p2;
wire   [0:0] tmp_mid2_fu_247_p3;
wire   [0:0] tmp_2_mid2_fu_267_p3;
wire   [0:0] tmp_9_fu_301_p2;
wire   [12:0] p_shl1_fu_344_p3;
wire   [10:0] p_shl2_fu_356_p3;
wire   [13:0] p_shl2_cast_fu_364_p1;
wire   [13:0] p_shl1_cast_fu_352_p1;
wire  signed [13:0] r_V_fu_368_p2;
wire  signed [15:0] grp_fu_566_p3;
wire   [21:0] tmp_fu_401_p3;
wire   [19:0] tmp_1_fu_413_p3;
wire  signed [23:0] p_shl4_cast_fu_421_p1;
wire  signed [23:0] p_shl3_cast_fu_409_p1;
wire  signed [23:0] grp_fu_538_p3;
wire  signed [23:0] mul_fu_456_p0;
wire   [47:0] mul_fu_456_p2;
wire   [47:0] neg_mul_fu_462_p2;
wire   [0:0] tmp_2_fu_468_p3;
wire   [16:0] tmp_3_fu_475_p4;
wire   [16:0] tmp_6_fu_485_p4;
wire   [16:0] p_v_v_fu_495_p3;
wire   [16:0] neg_ti_fu_503_p2;
wire   [7:0] tmp_10_fu_509_p1;
wire   [7:0] tmp_11_fu_513_p4;
wire   [7:0] tmp_12_fu_523_p3;
wire   [7:0] grp_fu_538_p1;
wire  signed [23:0] grp_fu_547_p3;
wire  signed [5:0] grp_fu_547_p1;
wire  signed [22:0] grp_fu_547_p2;
wire   [7:0] grp_fu_556_p0;
wire  signed [7:0] grp_fu_556_p1;
wire   [7:0] grp_fu_566_p0;
wire   [7:0] grp_fu_566_p1;
reg    ap_sig_cseq_ST_st5_fsm_2;
reg    ap_sig_410;
reg   [2:0] ap_NS_fsm;
wire  signed [23:0] grp_fu_547_p20;
wire   [15:0] grp_fu_556_p00;
wire   [15:0] grp_fu_566_p00;
reg    ap_sig_440;
reg    ap_sig_92;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'b1;
#0 window_V_0 = 8'b00000000;
#0 window_V_1 = 8'b00000000;
#0 window_V_2 = 8'b00000000;
#0 convolution_buffer_V_1 = 17'b00000000000000000;
#0 convolution_buffer_V_2 = 17'b00000000000000000;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ioackin_out_img_V_TREADY = 1'b0;
end

sep_convolution_filter_line_buffer_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_V_0_address0),
    .ce0(line_buffer_V_0_ce0),
    .q0(line_buffer_V_0_q0),
    .address1(line_buffer_V_0_addr_reg_598),
    .ce1(line_buffer_V_0_ce1),
    .we1(line_buffer_V_0_we1),
    .d1(line_buffer_V_1_q0)
);

sep_convolution_filter_line_buffer_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
line_buffer_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_V_1_address0),
    .ce0(line_buffer_V_1_ce0),
    .q0(line_buffer_V_1_q0),
    .address1(line_buffer_V_1_address1),
    .ce1(line_buffer_V_1_ce1),
    .we1(line_buffer_V_1_we1),
    .d1(in_temp_V_reg_613)
);

sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
sep_convolution_filter_mac_muladd_17s_8ns_24s_24_1_U1(
    .din0(convolution_buffer_V_2),
    .din1(grp_fu_538_p1),
    .din2(grp_fu_547_p3),
    .dout(grp_fu_538_p3)
);

sep_convolution_filter_mac_muladd_17s_6s_23s_24_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 23 ),
    .dout_WIDTH( 24 ))
sep_convolution_filter_mac_muladd_17s_6s_23s_24_1_U2(
    .din0(grp_fu_556_p3),
    .din1(grp_fu_547_p1),
    .din2(grp_fu_547_p2),
    .dout(grp_fu_547_p3)
);

sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
sep_convolution_filter_mac_muladd_8ns_8s_16s_17_1_U3(
    .din0(grp_fu_556_p0),
    .din1(grp_fu_556_p1),
    .din2(grp_fu_566_p3),
    .dout(grp_fu_556_p3)
);

sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 16 ))
sep_convolution_filter_mac_muladd_8ns_8ns_14s_16_1_U4(
    .din0(grp_fu_566_p0),
    .din1(grp_fu_566_p1),
    .din2(r_V_fu_368_p2),
    .dout(grp_fu_566_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_out_img_V_TREADY <= 1'b0;
    end else begin
        if (ap_sig_92) begin
            if (~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY)))) begin
                ap_reg_ioackin_out_img_V_TREADY <= 1'b0;
            end else if (ap_sig_440) begin
                ap_reg_ioackin_out_img_V_TREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(exitcond_flatten_fu_203_p2 == 1'b0))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_fu_203_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(exitcond_flatten_fu_203_p2 == 1'b0)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
            ap_reg_ppiten_pp0_it2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_203_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        col_reg_192 <= col_1_fu_313_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        col_reg_192 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_203_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        indvar_flatten_reg_170 <= indvar_flatten_next_fu_209_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        indvar_flatten_reg_170 <= ap_const_lv19_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_203_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        row_reg_181 <= row_mid2_fu_275_p3;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        row_reg_181 <= ap_const_lv9_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        ap_reg_ppstg_or_cond1_reg_619_pp0_iter1 <= or_cond1_reg_619;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_fu_203_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        col_mid2_reg_584 <= col_mid2_fu_221_p3;
        or_cond1_reg_619 <= or_cond1_fu_307_p2;
        or_cond_reg_609 <= or_cond_fu_295_p2;
        tmp_4_reg_594 <= tmp_4_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        convolution_buffer_V_1 <= convolution_buffer_V_2;
        convolution_buffer_V_2 <= grp_fu_556_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_fu_203_p2 == 1'b0) & ~(1'b0 == or_cond_fu_295_p2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        in_temp_V_reg_613 <= in_img_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (exitcond_flatten_fu_203_p2 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(1'b0 == tmp_4_fu_283_p2))) begin
        line_buffer_V_0_addr_reg_598 <= tmp_5_fu_289_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(1'b0 == tmp_4_reg_594))) begin
        window_V_0 <= line_buffer_V_0_q0;
        window_V_1 <= line_buffer_V_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(1'b0 == or_cond_reg_609))) begin
        window_V_2 <= in_temp_V_reg_613;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_69) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_20) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_410) begin
        ap_sig_cseq_ST_st5_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_out_img_V_TREADY)) begin
        ap_sig_ioackin_out_img_V_TREADY = out_img_V_TREADY;
    end else begin
        ap_sig_ioackin_out_img_V_TREADY = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_203_p2 == 1'b0) & ~(1'b0 == or_cond_fu_295_p2))) begin
        in_img_V_TDATA_blk_n = in_img_V_TVALID;
    end else begin
        in_img_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_203_p2 == 1'b0) & ~(1'b0 == or_cond_fu_295_p2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        in_img_V_TREADY = 1'b1;
    end else begin
        in_img_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_0_ce0 = 1'b1;
    end else begin
        line_buffer_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_0_ce1 = 1'b1;
    end else begin
        line_buffer_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(1'b0 == tmp_4_reg_594))) begin
        line_buffer_V_0_we1 = 1'b1;
    end else begin
        line_buffer_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_1_ce0 = 1'b1;
    end else begin
        line_buffer_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))))) begin
        line_buffer_V_1_ce1 = 1'b1;
    end else begin
        line_buffer_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_1) & (1'b1 == ap_reg_ppiten_pp0_it1) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(1'b0 == or_cond_reg_609))) begin
        line_buffer_V_1_we1 = 1'b1;
    end else begin
        line_buffer_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1))) begin
        out_img_V_TDATA_blk_n = out_img_V_TREADY;
    end else begin
        out_img_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) & (1'b0 == ap_reg_ioackin_out_img_V_TREADY))) begin
        out_img_V_TVALID = 1'b1;
    end else begin
        out_img_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_pp0_stg0_fsm_1 : begin
            if ((~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(1'b1 == ap_reg_ppiten_pp0_it1)) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(exitcond_flatten_fu_203_p2 == 1'b0) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end else if ((((1'b1 == ap_reg_ppiten_pp0_it2) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(1'b1 == ap_reg_ppiten_pp0_it1)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1) & (1'b0 == ap_sig_ioackin_out_img_V_TREADY))) & ~(exitcond_flatten_fu_203_p2 == 1'b0) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st5_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            end
        end
        ap_ST_st5_fsm_2 : begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

always @ (*) begin
    ap_sig_101 = ((exitcond_flatten_fu_203_p2 == 1'b0) & ~(1'b0 == or_cond_fu_295_p2) & (in_img_V_TVALID == 1'b0));
end

always @ (*) begin
    ap_sig_20 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_410 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_440 = (~((1'b1 == ap_reg_ppiten_pp0_it0) & ap_sig_101) & (1'b1 == out_img_V_TREADY));
end

always @ (*) begin
    ap_sig_69 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_92 = ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(1'b0 == ap_reg_ppstg_or_cond1_reg_619_pp0_iter1));
end

assign col_1_fu_313_p2 = (col_mid2_fu_221_p3 + ap_const_lv10_1);

assign col_mid2_fu_221_p3 = ((exitcond_fu_215_p2[0:0] === 1'b1) ? ap_const_lv10_0 : col_reg_192);

assign exitcond_flatten_fu_203_p2 = ((indvar_flatten_reg_170 == ap_const_lv19_4B461) ? 1'b1 : 1'b0);

assign exitcond_fu_215_p2 = ((col_reg_192 == ap_const_lv10_281) ? 1'b1 : 1'b0);

assign grp_fu_538_p1 = ap_const_lv24_47;

assign grp_fu_547_p1 = ap_const_lv23_7FFFEA;

assign grp_fu_547_p2 = grp_fu_547_p20;

assign grp_fu_547_p20 = ($signed(p_shl4_cast_fu_421_p1) - $signed(p_shl3_cast_fu_409_p1));

assign grp_fu_556_p0 = grp_fu_556_p00;

assign grp_fu_556_p00 = window_V_2;

assign grp_fu_556_p1 = ap_const_lv16_FF8E;

assign grp_fu_566_p0 = grp_fu_566_p00;

assign grp_fu_566_p00 = window_V_1;

assign grp_fu_566_p1 = ap_const_lv16_43;

assign indvar_flatten_next_fu_209_p2 = (indvar_flatten_reg_170 + ap_const_lv19_1);

assign line_buffer_V_0_address0 = tmp_5_fu_289_p1;

assign line_buffer_V_1_address0 = tmp_5_fu_289_p1;

assign line_buffer_V_1_address1 = tmp_8_fu_336_p1;

assign mul_fu_456_p0 = grp_fu_538_p3;

assign mul_fu_456_p2 = ($signed(mul_fu_456_p0) * $signed('h1020409));

assign neg_mul_fu_462_p2 = (ap_const_lv48_0 - mul_fu_456_p2);

assign neg_ti_fu_503_p2 = (ap_const_lv17_0 - p_v_v_fu_495_p3);

assign or_cond1_fu_307_p2 = (tmp_2_mid2_fu_267_p3 & tmp_9_fu_301_p2);

assign or_cond_fu_295_p2 = (tmp_4_fu_283_p2 & tmp_mid2_fu_247_p3);

assign out_img_V_TDATA = (tmp_12_fu_523_p3 + ap_const_lv8_3F);

assign p_shl1_cast_fu_352_p1 = p_shl1_fu_344_p3;

assign p_shl1_fu_344_p3 = {{window_V_0}, {ap_const_lv5_0}};

assign p_shl2_cast_fu_364_p1 = p_shl2_fu_356_p3;

assign p_shl2_fu_356_p3 = {{window_V_0}, {ap_const_lv3_0}};

assign p_shl3_cast_fu_409_p1 = $signed(tmp_fu_401_p3);

assign p_shl4_cast_fu_421_p1 = $signed(tmp_1_fu_413_p3);

assign p_v_v_fu_495_p3 = ((tmp_2_fu_468_p3[0:0] === 1'b1) ? tmp_3_fu_475_p4 : tmp_6_fu_485_p4);

assign r_V_fu_368_p2 = (p_shl2_cast_fu_364_p1 - p_shl1_cast_fu_352_p1);

assign row_mid2_fu_275_p3 = ((exitcond_fu_215_p2[0:0] === 1'b1) ? row_s_fu_229_p2 : row_reg_181);

assign row_s_fu_229_p2 = (row_reg_181 + ap_const_lv9_1);

assign tmp6_fu_241_p2 = ((row_reg_181 < ap_const_lv9_1E0) ? 1'b1 : 1'b0);

assign tmp_10_fu_509_p1 = neg_ti_fu_503_p2[7:0];

assign tmp_11_fu_513_p4 = {{mul_fu_456_p2[ap_const_lv32_26 : ap_const_lv32_1F]}};

assign tmp_12_fu_523_p3 = ((tmp_2_fu_468_p3[0:0] === 1'b1) ? tmp_10_fu_509_p1 : tmp_11_fu_513_p4);

assign tmp_1_fu_413_p3 = {{convolution_buffer_V_1}, {ap_const_lv3_0}};

assign tmp_2_fu_468_p3 = grp_fu_538_p3[ap_const_lv32_17];

assign tmp_2_mid1_fu_255_p2 = ((row_s_fu_229_p2 != ap_const_lv9_0) ? 1'b1 : 1'b0);

assign tmp_2_mid2_fu_267_p3 = ((exitcond_fu_215_p2[0:0] === 1'b1) ? tmp_2_mid1_fu_255_p2 : tmp_s_fu_261_p2);

assign tmp_3_fu_475_p4 = {{neg_mul_fu_462_p2[ap_const_lv32_2F : ap_const_lv32_1F]}};

assign tmp_4_fu_283_p2 = ((col_mid2_fu_221_p3 < ap_const_lv10_280) ? 1'b1 : 1'b0);

assign tmp_5_fu_289_p1 = col_mid2_fu_221_p3;

assign tmp_6_fu_485_p4 = {{mul_fu_456_p2[ap_const_lv32_2F : ap_const_lv32_1F]}};

assign tmp_8_fu_336_p1 = col_mid2_reg_584;

assign tmp_9_fu_301_p2 = ((col_mid2_fu_221_p3 != ap_const_lv10_0) ? 1'b1 : 1'b0);

assign tmp_fu_401_p3 = {{convolution_buffer_V_1}, {ap_const_lv5_0}};

assign tmp_mid1_fu_235_p2 = ((row_s_fu_229_p2 < ap_const_lv9_1E0) ? 1'b1 : 1'b0);

assign tmp_mid2_fu_247_p3 = ((exitcond_fu_215_p2[0:0] === 1'b1) ? tmp_mid1_fu_235_p2 : tmp6_fu_241_p2);

assign tmp_s_fu_261_p2 = ((row_reg_181 != ap_const_lv9_0) ? 1'b1 : 1'b0);

endmodule //sep_convolution_filter
